export interface SubService {
  title: string;
  slug: string;
  image: string;
  icon: string;
  description: string;
  longDescription: string;
  features: string[];
  process: string[];
  benefits: string[];
  stats: { value: string; label: string }[];
  faq: { question: string; answer: string }[];
  metaTitle: string;
  metaDescription: string;
}

export interface Service {
  key: string;
  title: string;
  subtitle: string;
  color: string;
  glowColor: string;
  shape: 'sphere' | 'cube' | 'octahedron' | 'torus' | 'diamond' | 'ring';
  description: string;
  /**
   * Kategori hub sayfasının gövde içeriği (`/hizmetler/[key]`).
   * 2 Ağu 2026'da eklendi: hub sayfaları 252-299 kelimeydi (hero paragrafı + kart
   * listesi + CTA), ticari sorgularda yarışacak hacim yoktu ve 36 sayfa GSC'de
   * "Discovered - currently not indexed" durumundaydı.
   * İçerik tavsiye/yöntem odaklıdır — uydurma müşteri metriği veya referans YOKTUR.
   */
  overview: { h2: string; body: string }[];
  /** Hub sayfasının SSS bloğu → FAQPage şeması + zengin sonuç. */
  faq: { question: string; answer: string }[];
  subServices: SubService[];
}

export const services: Service[] = [
  {
    key: 'ai',
    title: 'Yapay Zeka & Otomasyon',
    subtitle: 'Geleceği bugünden inşa edin',
    color: '#a78bfa',
    glowColor: 'rgba(167, 139, 250, 0.12)',
    shape: 'octahedron',
    description: 'İş süreçlerinizi yapay zeka ile dönüştürüyor, akıllı otomasyon çözümleriyle verimliliğinizi katlanarak artırıyoruz.',
    overview: [
      {
        h2: 'Yapay zeka bir işletmeye ne zaman gerçekten değer katar?',
        body: 'Yapay zeka her soruna uygun bir araç değildir. Değer ürettiği yer, tekrar eden, kural tabanlı ve hacimli işlerdir: her gün gelen yüzlerce benzer müşteri sorusu, elle girilen faturalar, farklı sistemler arasında kopyala-yapıştır yapılan veriler. Bu tür süreçlerde yapay zeka hem hatayı hem de harcanan saati düşürür. Buna karşılık ayda birkaç kez yapılan, her seferinde farklı yargı gerektiren işleri otomatikleştirmek genellikle kurulum maliyetini karşılamaz. Projeye başlamadan önce hangi sürecin ne kadar zaman aldığını ölçmenizi öneririz; otomasyonun geri dönüşü bu ölçümle hesaplanır, tahminle değil.',
      },
      {
        h2: 'Hazır platform mu, özel geliştirme mi?',
        body: 'Piyasada hazır chatbot ve otomasyon platformları var ve bazı ihtiyaçlar için doğru seçim onlardır. Hazır çözümler hızlı kurulur ve aylık abonelikle başlar; ancak veriniz üçüncü tarafta durur, özelleştirme sınırlıdır ve kullanıcı sayısı arttıkça maliyet doğrusal büyür. Özel geliştirme başlangıçta daha yüksek yatırım ister, buna karşılık kendi altyapınızda çalışır, mevcut ERP/CRM sisteminizle derin entegre olur ve büyüdükçe birim maliyeti düşer. Karar kriteri genellikle şudur: süreç işinizin ayırt edici bir parçasıysa özel geliştirme, standart bir destek hattıysa hazır platform daha mantıklıdır.',
      },
      {
        h2: 'Veri güvenliği ve KVKK tarafı',
        body: 'Yapay zeka projelerinin en çok atlanan boyutu veridir. Müşteri konuşmaları, fatura görselleri veya çalışan kayıtları kişisel veri içerir ve 6698 sayılı KVKK kapsamındadır. Kurduğumuz sistemlerde hangi verinin nerede işlendiği, ne kadar saklandığı ve yurt dışına aktarılıp aktarılmadığı en baştan tanımlanır. Dil modeli kullanılan senaryolarda, hassas alanların modele gönderilmeden önce maskelenmesi standart yaklaşımımızdır. Bu, hem yasal yükümlülük hem de pratik bir risk yönetimidir: bir kez dışarı çıkan veri geri alınamaz.',
      },
      {
        h2: 'Nasıl ilerliyoruz',
        body: 'Süreci küçük ve ölçülebilir başlatmayı tercih ediyoruz. Önce tek bir süreç seçilir, mevcut durumu ölçülür ve sınırlı kapsamlı bir pilot kurulur. Pilot gerçek kullanıcılarla çalıştıktan sonra elde edilen sayılar konuşur: yanıt süresi, insana devredilen konuşma oranı, işlem başına harcanan dakika. Sonuç beklentiyi karşılıyorsa kapsam genişletilir, karşılamıyorsa büyük bir yatırım yapılmadan yön değiştirilir. Bu yaklaşım, yapay zeka projelerinde en sık görülen hatayı — her şeyi aynı anda otomatikleştirmeye çalışıp hiçbirini tam bitirememeyi — önler.',
      },
    ],
    faq: [
      { question: 'Yapay zeka projesi ne kadar sürer?', answer: 'Kapsamla doğrudan ilişkilidir. Tek bir süreci kapsayan pilot uygulamalar genellikle 4-8 hafta içinde canlıya alınabilir. Birden fazla sistemle entegre olan, çok dilli veya özel model eğitimi gerektiren projeler 3-6 aya kadar uzayabilir. Süreyi en çok etkileyen faktör geliştirme değil, veriye erişim ve mevcut sistemlerin entegrasyona ne kadar açık olduğudur.' },
      { question: 'Yapay zeka çalışanların yerini mi alacak?', answer: 'Uygulamada gördüğümüz tablo bu değil. Otomasyon en çok, çalışanların zamanının büyük kısmını yiyen tekrar eden işlerde etkili oluyor; karar gerektiren, istisna içeren ve müşteriyle ilişki kuran işler insanda kalıyor. Doğru kurgulanmış bir projede ekip aynı kişi sayısıyla daha fazla işi, daha az hatayla karşılar. Amaç kadro azaltmak değil, kapasiteyi yükseltmektir.' },
      { question: 'Küçük bir işletme için yapay zeka pahalı değil mi?', answer: 'Tek seferde büyük bir sistem kurmaya çalışırsanız pahalıdır. Ancak tek bir dar süreçle başlayan projelerin bütçesi çok daha erişilebilirdir ve etkisi hızlı ölçülür. KOBİ\'ler için genellikle doğru başlangıç noktası, en çok zaman harcanan tek bir işi seçmek ve onu uçtan uca otomatikleştirmektir. Yatırımın karşılığı görüldükten sonra kapsam büyütülür.' },
      { question: 'Mevcut sistemlerimizle entegre olur mu?', answer: 'Çoğu durumda evet. Muhasebe programları, ERP, CRM, e-ticaret altyapıları ve çağrı merkezi yazılımlarının büyük bölümü API sunar. API bulunmayan eski sistemlerde veritabanı seviyesinde veya dosya tabanlı entegrasyon yöntemleri kullanılabilir. Projeye başlamadan önce mevcut sistemlerinizin entegrasyon kabiliyetini inceleyip somut bir yol haritası çıkarıyoruz.' },
      { question: 'Yapay zekanın verdiği yanlış cevaplardan nasıl korunuruz?', answer: 'Dil modelleri kendinden emin görünen yanlış cevaplar üretebilir; bu bilinen bir risktir ve tasarımla yönetilir. Kullandığımız yöntemler: modelin yalnızca sizin doğrulanmış içeriğinizden cevap üretmesi, emin olmadığı durumda konuşmayı insana devretmesi ve kritik işlemlerde onay adımı bulunması. Ayrıca canlıya alındıktan sonra konuşmalar düzenli olarak gözden geçirilir ve sistem buna göre iyileştirilir.' },
    ],
    subServices: [
      {
        title: 'AI Chatbot & Asistan',
        slug: 'ai-chatbot-asistan',
        image: '🤖',
        icon: 'chatbot',
        description: 'Müşteri hizmetlerini 7/24 yapay zeka destekli chatbot ve sanal asistanlarla otomatikleştirin.',
        longDescription: 'Doğal dil işleme teknolojileri sayesinde karmaşık soruları anlayan, bağlamı kavrayan ve insan benzeri yanıtlar üreten akıllı sohbet sistemleri geliştiriyoruz. CRM, ERP ve mevcut iş süreçlerinizle tam entegre çalışan chatbotlarımız, müşteri hizmetleri maliyetlerinizi %60\'a kadar düşürürken müşteri deneyimini üst seviyeye taşır. Çok dilli destek ve duygu analizi ile küresel ölçekte hizmet verin.',
        features: ['Doğal Dil İşleme (NLP)', 'Çok dilli destek (50+ dil)', 'CRM/ERP entegrasyonu', 'Öğrenen algoritma', 'Duygu analizi & sentiment', 'Sesli asistan desteği'],
        process: ['İhtiyaç analizi ve senaryo tasarımı', 'AI modeli eğitimi ve kişiselleştirme', 'Entegrasyon ve kapsamlı test süreci', 'Canlıya alma ve sürekli optimizasyon'],
        benefits: ['Müşteri hizmetleri maliyetlerinde %60 tasarruf', '7/24 kesintisiz, anında müşteri desteği', 'Artan müşteri memnuniyeti ve marka bağlılığı'],
        stats: [{ value: 'NLP', label: 'Doğal Dil İşleme' }, { value: 'Çok Kanallı', label: 'Web · WhatsApp · Sosyal' }, { value: 'CRM', label: 'Sistem Entegrasyonu' }, { value: 'Sürekli', label: 'İyileştirme ve Bakım' }],
        faq: [
          { question: 'AI chatbot nedir ve nasıl çalışır?', answer: 'AI chatbot, doğal dil işleme (NLP) teknolojisi kullanarak müşterilerinizle metin veya ses aracılığıyla iletişim kuran yapay zeka yazılımıdır. Kullanıcıların sorularını anlayarak bağlama uygun yanıtlar üretir ve her etkileşimde öğrenerek kendini geliştirir.' },
          { question: 'Chatbot geliştirme süreci ne kadar sürer?', answer: 'Projenin kapsamına bağlı olarak chatbot geliştirme süreci genellikle 4-12 hafta arasında sürer. Basit senaryolar için 4 hafta yeterli olurken, çok dilli ve CRM entegrasyonlu kapsamlı projeler 8-12 hafta sürebilir.' },
          { question: 'Chatbot hangi platformlarla entegre olabilir?', answer: 'Chatbotlarımız WhatsApp, Telegram, Facebook Messenger, web siteniz, mobil uygulamanız ve CRM/ERP sistemleriniz dahil 50\'den fazla platformla sorunsuz entegre çalışır.' },
          { question: 'AI chatbot yatırım getirisi nedir?', answer: 'Müşterilerimiz ortalama %60 maliyet tasarrufu ve %35 müşteri memnuniyeti artışı elde etmektedir. İlk 3 ayda yatırımın geri dönüşü sağlanır.' },
        ],
        metaTitle: 'AI Chatbot & Asistan Geliştirme | BERACORE',
        metaDescription: 'Yapay zeka destekli chatbot ve sanal asistanla müşteri hizmetini 7/24 otomatikleştirin. NLP, çok dilli destek, CRM entegrasyonu. AI chatbot: BERACORE.',
      },
      {
        title: 'Süreç Otomasyonu',
        slug: 'surec-otomasyonu',
        image: '⚙️',
        icon: 'gear',
        description: 'Tekrarlayan iş süreçlerini RPA ve AI ile otomatikleştirerek operasyonel verimliliğinizi artırın.',
        longDescription: 'Robotic Process Automation (RPA) ve yapay zeka teknolojilerini birleştirerek, manuel iş süreçlerinizi uçtan uca otomatikleştiriyoruz. Fatura işleme, veri girişi, raporlama ve onay süreçleri gibi tekrarlayan görevleri dakikalar içinde tamamlayan akıllı botlar geliştiriyoruz. İnsan hatasını sıfıra indirirken çalışanlarınızın yaratıcı ve stratejik işlere odaklanmasını sağlıyoruz.',
        features: ['RPA bot geliştirme', 'İş akışı tasarımı & orkestrasyon', 'Raporlama & analitik dashboard', 'API otomasyon & webhook', 'Belge işleme (OCR/IDP)', 'Akıllı karar motorları'],
        process: ['Süreç haritalama ve otomasyon potansiyeli analizi', 'Bot geliştirme ve iş akışı tasarımı', 'Pilot uygulama ve performans testi', 'Tam ölçekli dağıtım ve izleme'],
        benefits: ['Operasyonel maliyetlerde %40-70 düşüş', 'İnsan hatasının tamamen ortadan kaldırılması', 'Çalışan verimliliğinde 3x artış'],
        stats: [{ value: 'RPA', label: 'Robotik Süreç Otomasyonu' }, { value: 'Uçtan Uca', label: 'Süreç Analizi' }, { value: 'ERP · CRM', label: 'Sistem Bağlantısı' }, { value: 'Raporlu', label: 'Çalışma Takibi' }],
        faq: [
          { question: 'RPA (Robotik Süreç Otomasyonu) nedir?', answer: 'RPA, tekrarlayan ve kural tabanlı iş süreçlerini yazılım robotları ile otomatikleştiren bir teknolojidir. İnsan müdahalesi olmadan veri girişi, form doldurma, rapor oluşturma gibi görevleri yerine getirir.' },
          { question: 'Hangi iş süreçleri otomatikleştirilebilir?', answer: 'Fatura işleme, sipariş yönetimi, veri aktarımı, raporlama, müşteri onboarding, envanter güncelleme ve daha birçok tekrarlayan süreç RPA ile otomatikleştirilebilir.' },
          { question: 'Otomasyon ne kadar sürede devreye alınır?', answer: 'Basit otomasyon senaryoları 2-4 haftada, kapsamlı iş akışı otomasyonları 6-12 haftada devreye alınır. Pilot uygulama ile başlayarak kademeli bir yaklaşım izliyoruz.' },
          { question: 'Mevcut sistemlerimizle uyumlu çalışır mı?', answer: 'RPA botlarımız ERP, CRM, e-posta, veritabanları ve web uygulamaları dahil mevcut tüm sistemlerinizle API veya arayüz düzeyinde entegre çalışır.' },
        ],
        metaTitle: 'Süreç Otomasyonu & RPA Çözümleri | BERACORE',
        metaDescription: 'İş süreçlerinizi RPA ve yapay zeka ile otomatikleştirin. Maliyet tasarrufu, sıfır hata, 3x verimlilik artışı. Kurumsal süreç otomasyonu çözümleri için BERACORE.',
      },
      {
        title: 'AI Veri Analizi',
        slug: 'ai-veri-analizi',
        image: '📊',
        icon: 'chart',
        description: 'Büyük veri setlerinden anlamlı içgörüler çıkarın. Tahmine dayalı analitik ile stratejik kararlar alın.',
        longDescription: 'Petabaytlarca veriyi saniyeler içinde analiz eden, kalıpları ve trendleri keşfeden güçlü AI modelleri geliştiriyoruz. Gerçek zamanlı dashboard\'lar ve interaktif görselleştirmeler ile verileriniz anında aksiyona dönüşür. Tahmine dayalı analitik ile müşteri davranışlarını, pazar trendlerini ve riskleri önceden görerek rakiplerinizin bir adım önünde olun.',
        features: ['Tahmine dayalı analitik (predictive)', 'Gerçek zamanlı veri dashboard\'ı', 'İnteraktif veri görselleştirme', 'Makine öğrenmesi modelleri', 'Anomali ve sahtekarlık tespiti', 'Otomatik rapor üretimi'],
        process: ['Veri kaynaklarının haritalanması ve entegrasyonu', 'Veri temizleme ve model eğitimi', 'Dashboard ve görselleştirme tasarımı', 'Deployment ve sürekli model iyileştirme'],
        benefits: ['Veriye dayalı stratejik karar alma kapasitesi', 'Pazar trendlerini önceden tahmin edebilme', 'Gelir artışı ve maliyet optimizasyonu'],
        stats: [{ value: 'Tahminleme', label: 'Makine Öğrenmesi' }, { value: 'Canlı Pano', label: 'Veri Görselleştirme' }, { value: 'Çok Kaynak', label: 'Veri Birleştirme' }, { value: 'Otomatik', label: 'Periyodik Raporlama' }],
        faq: [
          { question: 'AI veri analizi işletmeme ne katar?', answer: 'AI veri analizi, büyük veri setlerinden insan gözünün kaçıracağı kalıpları ve trendleri ortaya çıkarır. Bu sayede stratejik kararlarınızı veriye dayalı alır, riskleri önceden tespit eder ve yeni fırsatları keşfedersiniz.' },
          { question: 'Hangi veri kaynaklarını analiz edebilirsiniz?', answer: 'Veritabanları, CRM sistemleri, web analitiği, sosyal medya, IoT sensörleri, ERP ve daha birçok kaynaktan veri toplayarak bütünleşik analiz yapıyoruz.' },
          { question: 'Tahmine dayalı analitik ne işe yarar?', answer: 'Tahmine dayalı analitik, geçmiş verilerden öğrenen makine öğrenmesi modelleri ile gelecekteki müşteri davranışlarını, satış trendlerini ve olası riskleri önceden tahmin etmenizi sağlar.' },
          { question: 'Dashboard ve raporlara nasıl erişirim?', answer: 'Web tabanlı interaktif dashboard\'larımıza herhangi bir cihazdan erişebilirsiniz. Otomatik rapor üretimi ile belirlediğiniz periyodlarda e-posta ile raporlar alırsınız.' },
        ],
        metaTitle: 'AI Veri Analizi & Tahmine Dayalı Analitik | BERACORE',
        metaDescription: 'Yapay zeka destekli veri analizi ile büyük veriden içgörü çıkarın. Gerçek zamanlı dashboard, tahmine dayalı analitik, makine öğrenmesi. BERACORE veri analizi.',
      },
      {
        title: 'Özel AI Çözümleri',
        slug: 'ozel-ai-cozumleri',
        image: '🧠',
        icon: 'brain',
        description: 'İşletmenize özel yapay zeka modelleri ve çözümleri geliştiriyoruz.',
        longDescription: 'Sektörünüze ve iş modelinize özel, sıfırdan tasarlanan yapay zeka çözümleri sunuyoruz. Görüntü ve ses işleme, doğal dil anlama, öneri sistemleri ve anomali tespiti gibi ileri düzey AI uygulamalarını işletmenize entegre ediyoruz. Ölçeklenebilir bulut altyapısı üzerinde çalışan modellerimiz, büyümenizle birlikte gelişir ve sürekli öğrenir.',
        features: ['Özel model eğitimi & fine-tuning', 'Görüntü işleme & bilgisayarlı görü', 'Ses tanıma & sentezleme', 'Kişiselleştirilmiş öneri sistemleri', 'Anomali & sahtekarlık tespiti', 'Edge AI & IoT entegrasyonu'],
        process: ['Kullanım senaryosu tanımlama ve fizibilite', 'Veri toplama, etiketleme ve model tasarımı', 'Prototip geliştirme ve performans testi', 'Üretim ortamına deployment ve monitoring'],
        benefits: ['Sektöre özel, rakiplerden farklılaşan AI çözümleri', 'Ölçeklenebilir ve sürekli öğrenen modeller', 'Tam entegre, uçtan uca AI altyapısı'],
        stats: [{ value: 'Özel Model', label: 'İhtiyaca Göre Eğitim' }, { value: 'API', label: 'Sisteme Entegrasyon' }, { value: 'İzlenebilir', label: 'Model Performansı' }, { value: 'KVKK', label: 'Veri Uyumu' }],
        faq: [
          { question: 'Özel AI çözümü ne zaman gereklidir?', answer: 'Hazır AI ürünleri iş ihtiyaçlarınızı karşılayamadığında, sektöre özel veri ve süreçleriniz olduğunda veya rakiplerden farklılaşmak istediğinizde özel AI çözümü gerekir.' },
          { question: 'AI model eğitimi için ne kadar veriye ihtiyaç var?', answer: 'Gerekli veri miktarı probleme göre değişir. Genellikle binlerce etiketli veri noktası yeterlidir. Transfer learning ile daha az veriyle bile yüksek performanslı modeller geliştirebiliyoruz.' },
          { question: 'AI çözümü mevcut altyapımla çalışır mı?', answer: 'Evet. Bulut (AWS, Azure, GCP) veya on-premise altyapınız üzerinde çalışan AI çözümleri geliştiriyoruz. API\'ler aracılığıyla mevcut sistemlerinize sorunsuz entegre olur.' },
          { question: 'Model performansı nasıl izlenir?', answer: '7/24 model monitoring sistemi ile performans metriklerini takip ediyor, veri kaymasını tespit ediyor ve gerektiğinde modeli otomatik olarak yeniden eğitiyoruz.' },
        ],
        metaTitle: 'Özel Yapay Zeka Çözümleri Geliştirme | BERACORE',
        metaDescription: 'İşletmenize özel AI modelleri geliştirin. Görüntü işleme, ses tanıma, öneri sistemleri, anomali tespiti. Sektöre özel yapay zeka çözümleri için BERACORE.',
      },
    ],
  },
  {
    key: 'blockchain',
    title: 'Blockchain & Fintech',
    subtitle: 'Finansın yeni mimarisi',
    color: '#7dd3fc',
    glowColor: 'rgba(125, 211, 252, 0.12)',
    shape: 'cube',
    description: 'Kripto para borsası, akıllı kontrat ve merkeziyetsiz finans çözümleriyle dijital finansın altyapısını kuruyoruz.',
    overview: [
      {
        h2: 'Blockchain gerçekten gerekli mi, yoksa veritabanı yeter mi?',
        body: 'Dürüst cevap: çoğu proje için normal bir veritabanı yeterlidir ve daha ucuzdur. Blockchain, birbirine güvenmeyen birden fazla tarafın aynı kaydı paylaşması gerektiğinde, kaydın sonradan değiştirilemez olması kritik olduğunda ve aracıyı ortadan kaldırmanın somut bir değeri olduğunda anlam kazanır. Tedarik zincirinde köken takibi, çok taraflı mutabakat, dijital varlık transferi bu tanıma uyar. Sadece \'modern görünsün\' diye blockchain kullanmak maliyeti ve karmaşıklığı gereksiz yere artırır. Bir projeye başlamadan önce bu soruyu açıkça sorup, cevabı hayırsa size bunu söyleriz.',
      },
      {
        h2: 'Akıllı kontratlarda güvenlik pazarlık konusu değildir',
        body: 'Akıllı kontratlar yayınlandıktan sonra çoğu durumda değiştirilemez ve doğrudan para taşır. Bu ikisi bir araya geldiğinde, sıradan yazılımda küçük sayılacak bir hata geri alınamaz kayba dönüşür. Bu yüzden kontrat geliştirmede test kapsamı, bilinen saldırı desenlerine (yeniden giriş, tam sayı taşması, yetki kontrolü eksikliği, fiyat manipülasyonu) karşı kontrol ve bağımsız denetim isteğe bağlı adımlar değildir. Yükseltilebilir kontrat mimarisi kullanılacaksa, yükseltme yetkisinin kimde olduğu ve nasıl korunduğu en kritik tasarım kararıdır.',
      },
      {
        h2: 'Fintech tarafında düzenleme gerçeği',
        body: 'Türkiye\'de ödeme, elektronik para ve kripto varlık hizmet sağlayıcılığı düzenlemeye tabidir; bazı faaliyetler lisans gerektirir. Teknik olarak yapılabilir olan her şey hukuki olarak serbest değildir. Bu nedenle fintech projelerinde mimariyi kurmadan önce iş modelinin hangi düzenleme kapsamına girdiğinin netleşmesi gerekir. Biz yazılım tarafını üstleniyoruz; lisans ve hukuki uygunluk için alanında uzman danışmanla çalışmanızı öneriyoruz. Bu ayrımı baştan yapmak, ilerleyen aşamada baştan yazılması gereken bir sistemden çok daha ucuzdur.',
      },
      {
        h2: 'Nasıl ilerliyoruz',
        body: 'Blockchain projelerinde en pahalı hata, yanlış zincir veya yanlış mimariyle başlayıp aylar sonra geri dönmektir. Bu yüzden ilk aşama teknoloji seçimi değil, ihtiyaç analizidir: kaç taraf var, işlem hacmi ne, gizlilik gereksinimi nedir, kullanıcı cüzdan yönetecek mi. Bu cevaplar zincir seçimini (herkese açık, izinli veya katman-2) belirler. Ardından küçük ve test ağında çalışan bir prototip çıkarılır, denetimden geçirilir ve ancak sonra ana ağa alınır.',
      },
    ],
    faq: [
      { question: 'Akıllı kontrat geliştirme ne kadar sürer?', answer: 'Standart bir token veya basit kilit kontratı birkaç hafta içinde tamamlanabilir. Çok adımlı iş mantığı içeren, harici veri kaynağı kullanan veya birden fazla kontratın birbiriyle konuştuğu sistemler 2-4 ay sürer. Bu sürenin önemli bir kısmı geliştirmeden çok test ve denetime ayrılır; akıllı kontratlarda bu adım kısaltılmaz.' },
      { question: 'Akıllı kontrat denetimi şart mı?', answer: 'Gerçek değer taşıyacak her kontrat için evet. Kontrat yayınlandıktan sonra hatayı düzeltme imkânı çoğu zaman yoktur ve açıklar otomatik botlar tarafından dakikalar içinde bulunur. Bağımsız denetim ek bir maliyettir, ancak olası kaybın yanında küçük kalır. Denetim öncesi kendi test ve kontrol sürecimizi tamamlayarak denetim maliyetini ve bulgu sayısını düşürüyoruz.' },
      { question: 'Hangi blockchain ağını seçmeliyiz?', answer: 'Seçim; işlem maliyeti, hız, güvenlik ve ekosistem büyüklüğü arasındaki dengeye göre yapılır. Yüksek güvenlik ve geniş ekosistem önceliğinizse Ethereum, düşük işlem maliyeti önemliyse katman-2 çözümleri veya alternatif ağlar, verinin yalnızca belirli kurumlar arasında paylaşılması gerekiyorsa izinli (permissioned) ağlar öne çıkar. Doğru cevap projeye göre değişir; tek bir ağı her projeye önermiyoruz.' },
      { question: 'Kripto para borsası kurmak için neler gerekir?', answer: 'Teknik tarafta eşleştirme motoru, cüzdan altyapısı, güvenlik katmanı ve gerçek zamanlı veri akışı gerekir. Ancak asıl belirleyici olan düzenleme tarafıdır: müşteri tanıma (KYC), kara para aklamayla mücadele yükümlülükleri ve ilgili lisanslar. Bu nedenle borsa projelerinde yazılım geliştirmeyle hukuki süreci paralel yürütmek gerekir.' },
      { question: 'Blockchain projesi mevcut sistemimize entegre edilebilir mi?', answer: 'Evet. Pratikte yaygın olan yaklaşım, blockchain\'i mevcut sistemin yerine koymak değil, yanına eklemektir: kritik kayıtlar zincire yazılır, günlük operasyon mevcut veritabanında yürür. Bu hem maliyeti düşürür hem geçişi kademeli hale getirir.' },
    ],
    subServices: [
      {
        title: 'Kripto Para Borsası Yazılımı',
        slug: 'kripto-para-borsasi-yazilimi',
        image: '💰',
        icon: 'coin',
        description: 'Güvenli, yüksek performanslı ve ölçeklenebilir kripto para borsası platformları geliştiriyoruz.',
        longDescription: 'Saniyede yüzbinlerce işlemi sorunsuz yönetebilen, kurumsal düzeyde güvenlik altyapısına sahip kripto para borsası platformları geliştiriyoruz. Spot, futures, marjin ve OTC işlem desteği ile tam kapsamlı bir trading deneyimi sunun. Soğuk/sıcak cüzdan sistemi, çok katmanlı güvenlik ve KYC/AML uyumluluk modülleriyle regülatör gereksinimleri karşılayın.',
        features: ['Yüksek frekanslı trade engine (100K+ TPS)', 'Soğuk/sıcak cüzdan yönetim sistemi', 'KYC/AML uyumluluk modülü', 'Likidite havuzu & market maker', 'Spot, futures & marjin trading', 'Gerçek zamanlı order book & charting'],
        process: ['Borsa mimarisi tasarımı ve güvenlik planlaması', 'Core engine, cüzdan ve eşleştirme motoru geliştirme', 'Güvenlik denetimi ve penetrasyon testi', 'Kademeli lansman ve likidite yönetimi'],
        benefits: ['Saniyede 100.000+ işlem kapasitesi', 'Kurumsal düzeyde çok katmanlı güvenlik', 'Uluslararası regülasyonlara tam uyumluluk'],
        stats: [{ value: '256-bit', label: 'Şifreleme' }, { value: 'Soğuk Cüzdan', label: 'Varlık Saklama' }, { value: 'Emir Defteri', label: 'Eşleştirme Motoru' }, { value: 'KYC · AML', label: 'Kimlik Doğrulama' }],
        faq: [
          { question: 'Kripto para borsası geliştirmek ne kadar sürer?', answer: 'Tam kapsamlı bir kripto para borsası geliştirme süreci 4-8 ay arasında sürer. MVP (Minimum Viable Product) yaklaşımıyla 3 ayda temel özellikleri devreye alıp kademeli olarak genişletebiliriz.' },
          { question: 'Borsa güvenliği nasıl sağlanır?', answer: 'Çok katmanlı güvenlik mimarisi kullanıyoruz: soğuk cüzdan depolama, 2FA, IP whitelisting, DDoS koruması, penetrasyon testleri ve 7/24 güvenlik izleme ile fonlarınız koruma altında.' },
          { question: 'Hangi blockchain ağlarını destekliyorsunuz?', answer: 'Bitcoin, Ethereum, Solana, BNB Chain, Polygon, Avalanche ve daha 50+ blockchain ağını destekliyoruz. Yeni ağlar talep üzerine hızla entegre edilir.' },
          { question: 'Regülasyonlara uyum nasıl sağlanır?', answer: 'KYC/AML modülümüz uluslararası regülasyonlara uygun şekilde tasarlanmıştır. Kimlik doğrulama, işlem izleme ve raporlama araçları ile yasal gereksinimleri karşılarsınız.' },
        ],
        metaTitle: 'Kripto Para Borsası Yazılımı Geliştirme | BERACORE',
        metaDescription: 'Güvenli ve yüksek performanslı kripto para borsası yazılımı geliştirme. 100K+ TPS, KYC/AML uyumluluk, soğuk cüzdan sistemi. BERACORE blockchain çözümleri.',
      },
      {
        title: 'Akıllı Kontrat Geliştirme',
        slug: 'akilli-kontrat-gelistirme',
        image: '📜',
        icon: 'contract',
        description: 'Ethereum, Solana ve diğer blockchain ağlarında güvenli akıllı kontratlar geliştiriyoruz.',
        longDescription: 'Solidity, Rust ve Move dilleriyle güvenlik odaklı akıllı kontratlar yazıyoruz. Her kontrat, bağımsız güvenlik denetiminden geçer ve gas optimizasyonu ile maliyetler minimize edilir. Upgradeable proxy pattern, multisig mekanizmaları ve DAO yönetişim yapıları ile projelerinizi geleceğe hazırlıyoruz.',
        features: ['Solidity, Rust & Move geliştirme', 'Bağımsız güvenlik denetimi (audit)', 'Gas optimizasyonu & maliyet kontrolü', 'Upgradeable proxy kontratlar', 'Multisig & timelock mekanizmaları', 'Formal verification & test suite'],
        process: ['Kontrat gereksinimlerinin belirlenmesi', 'Akıllı kontrat geliştirme ve birim testleri', 'Üçüncü parti güvenlik denetimi', 'Mainnet deployment ve doğrulama'],
        benefits: ['%100 güvenlik denetimli kontratlar', 'Optimize edilmiş gas maliyetleri', 'Gelecek uyumlu, yükseltilebilir mimari'],
        stats: [{ value: 'Solidity', label: 'Kontrat Geliştirme' }, { value: 'Testli', label: 'Otomatik Kontrat Testi' }, { value: 'Gas', label: 'Maliyet Optimizasyonu' }, { value: 'Audit', label: 'Denetime Hazır Kod' }],
        faq: [
          { question: 'Akıllı kontrat nedir?', answer: 'Akıllı kontrat, blockchain üzerinde çalışan ve önceden tanımlanan koşullar sağlandığında otomatik olarak yürütülen dijital sözleşmelerdir. Aracıya gerek kalmadan güvenli işlemler yapmanızı sağlar.' },
          { question: 'Akıllı kontrat güvenlik denetimi neden önemlidir?', answer: 'Blockchain işlemleri geri alınamaz olduğundan, güvenlik açıkları büyük kayıplara yol açabilir. Bağımsız güvenlik denetimi, kontratınızdaki olası açıkları tespit ederek fonlarınızı korur.' },
          { question: 'Hangi blockchain ağlarında geliştirme yapıyorsunuz?', answer: 'Ethereum, Solana, BNB Chain, Polygon, Avalanche, Arbitrum ve Optimism başta olmak üzere tüm popüler EVM ve non-EVM ağlarda geliştirme yapıyoruz.' },
          { question: 'Upgradeable kontrat ne demektir?', answer: 'Upgradeable kontratlar, proxy pattern kullanarak mantık kodunun güncellenmesine olanak tanır. Böylece kontratınızı yeniden deploy etmeden yeni özellikler ekleyebilir veya hataları düzeltebilirsiniz.' },
        ],
        metaTitle: 'Akıllı Kontrat Geliştirme & Audit | BERACORE',
        metaDescription: 'Güvenli akıllı kontrat geliştirme ve denetim hizmetleri. Solidity, Rust, gas optimizasyonu, güvenlik auditi. Ethereum, Solana blockchain geliştirme. BERACORE.',
      },
      {
        title: 'DeFi & Token Çözümleri',
        slug: 'defi-token-cozumleri',
        image: '🔗',
        icon: 'chain',
        description: 'Merkeziyetsiz finans protokolleri ve token ekonomileri tasarlıyoruz.',
        longDescription: 'Staking, yield farming, likidite havuzları ve merkeziyetsiz borsa (DEX) protokolleri geliştiriyoruz. Token ekonomisi tasarımından DAO yönetişim yapısına kadar DeFi ekosisteminizin tüm katmanlarını inşa ediyoruz. ERC-20, ERC-721 ve ERC-1155 standartlarında token oluşturma, airdrop mekanizmaları ve vesting schedule yönetimi sunuyoruz.',
        features: ['Token oluşturma (ERC-20/721/1155)', 'DEX & AMM protokol geliştirme', 'Staking & yield farming mekanizmaları', 'DAO yönetişim altyapısı', 'Likidite havuzu yönetimi', 'Tokenomik tasarım & danışmanlık'],
        process: ['Token ekonomisi ve protokol tasarımı', 'Akıllı kontrat geliştirme ve denetim', 'Frontend ve kullanıcı arayüzü entegrasyonu', 'Lansman, likidite sağlama ve topluluk oluşturma'],
        benefits: ['Profesyonel tokenomik tasarım ve danışmanlık', 'Güvenli ve denetlenmiş DeFi protokolleri', 'Sürdürülebilir token ekonomisi ve yönetişim'],
        stats: [{ value: 'ERC-20', label: 'Token Standartları' }, { value: 'Likidite', label: 'Havuz Kurulumu' }, { value: 'DEX', label: 'Borsa Entegrasyonu' }, { value: 'Audit', label: 'Denetime Hazır Kod' }],
        faq: [
          { question: 'DeFi nedir ve nasıl çalışır?', answer: 'DeFi (Merkeziyetsiz Finans), blockchain teknolojisi üzerinde aracısız finansal hizmetler sunan protokollerdir. Borç verme, ödünç alma, takas ve likidite sağlama gibi finansal işlemleri akıllı kontratlar aracılığıyla gerçekleştirir.' },
          { question: 'Token oluşturma süreci nasıl işler?', answer: 'Token oluşturma; tokenomik tasarım, akıllı kontrat geliştirme, güvenlik denetimi ve deployment aşamalarından oluşur. ERC-20, ERC-721 veya ERC-1155 standartlarından projenize uygun olanı seçeriz.' },
          { question: 'DAO yönetişimi nedir?', answer: 'DAO (Decentralized Autonomous Organization), token sahiplerinin oylama yoluyla projenin geleceğini belirledikleri merkeziyetsiz yönetim yapısıdır. Şeffaf ve topluluk odaklı karar alma mekanizması sağlar.' },
          { question: 'Likidite havuzu nasıl oluşturulur?', answer: 'Uniswap, PancakeSwap gibi DEX\'lerde likidite havuzu oluşturuyoruz. Token çiftiniz için AMM (Automated Market Maker) mekanizması kurarak kullanıcıların sorunsuz token takası yapmasını sağlıyoruz.' },
        ],
        metaTitle: 'DeFi & Token Geliştirme Çözümleri | BERACORE',
        metaDescription: 'DeFi protokol geliştirme, token oluşturma, staking, yield farming ve DAO yönetişim çözümleri. Profesyonel tokenomik tasarım. BERACORE blockchain hizmetleri.',
      },
      {
        title: 'Ödeme Altyapısı',
        slug: 'odeme-altyapisi',
        image: '💳',
        icon: 'creditcard',
        description: 'Kripto ve fiat ödeme altyapıları kuruyoruz. PCI DSS sertifikalı sağlayıcılarla entegre, güvenli ve hızlı ödeme çözümleri.',
        longDescription: 'Kripto para ve geleneksel fiat para birimlerini tek bir altyapıda birleştiren ödeme gateway çözümleri geliştiriyoruz. Kart verisi PCI DSS Level 1 sertifikalı sağlayıcıda işlenir; sizin sisteminizde saklanmaz. On-ramp ve off-ramp çözümleri ile kullanıcılarınız kripto ve fiat arasında sorunsuz geçiş yapabilir.',
        features: ['Kripto ödeme gateway entegrasyonu', 'Fiat on-ramp & off-ramp çözümleri', 'PCI DSS Level 1 sertifikalı sağlayıcı entegrasyonu', 'Çoklu para birimi desteği (150+)', 'Anlık ödeme bildirimleri & webhook', 'Sahtekarlık tespit & önleme sistemi'],
        process: ['Ödeme akışı tasarımı ve güvenlik planlaması', 'Gateway entegrasyonu ve API geliştirme', 'Compliance ve güvenlik sertifikasyonu', 'Pilot test ve kademeli canlıya alma'],
        benefits: ['Kart verisi sizde saklanmaz — sorumluluk sertifikalı sağlayıcıda', 'Küresel ölçekte 150+ para birimi desteği', 'Düşük işlem ücretleri ve anlık settlement'],
        stats: [{ value: '3D Secure', label: 'Güvenli Doğrulama' }, { value: 'Sanal POS', label: 'Banka Entegrasyonu' }, { value: 'Taksit', label: 'Ödeme Seçenekleri' }, { value: 'Mutabakat', label: 'Otomatik Raporlama' }],
        faq: [
          { question: 'Kripto ödeme altyapısı nasıl çalışır?', answer: 'Kripto ödeme altyapımız, müşterilerinizin Bitcoin, Ethereum ve diğer kripto paralarla ödeme yapmasını sağlar. Anlık kur dönüştürme ile isterseniz ödemeleri otomatik olarak fiat para birimine çevirebilirsiniz.' },
          { question: 'PCI DSS uyumluluk neden önemlidir?', answer: 'PCI DSS, kart verilerinin güvenliğini sağlayan uluslararası standarttır. Sertifikayı kart verisini işleyen taraf taşır; bu yüzden altyapıyı, kart verisi sizin sisteminize hiç girmeyecek şekilde PCI DSS Level 1 sertifikalı sağlayıcılar üzerinden kurgularız. Böylece sertifikasyon yükü sizde olmaz.' },
          { question: 'Hangi ödeme yöntemlerini destekliyorsunuz?', answer: 'Kredi/banka kartı, havale/EFT, kripto para, mobil cüzdan, QR kod ödeme ve BNPL (şimdi al sonra öde) dahil 150+ ödeme yöntemini destekliyoruz.' },
          { question: 'Entegrasyon süreci ne kadar sürer?', answer: 'Standart API entegrasyonu 1-2 hafta, kapsamlı özel ödeme altyapısı 4-8 hafta içinde tamamlanır. Detaylı dokümantasyon ve teknik destek sağlıyoruz.' },
        ],
        metaTitle: 'Ödeme Altyapısı & Kripto Ödeme Gateway | BERACORE',
        metaDescription: 'Kripto ve fiat ödeme altyapısı çözümleri. PCI DSS sertifikalı sağlayıcı entegrasyonu, çoklu para birimi, anlık settlement. BERACORE fintech hizmetleri.',
      },
    ],
  },
  {
    key: 'software',
    title: 'Yazılım Geliştirme',
    subtitle: 'Güçlü altyapı, temiz kod',
    color: '#f0abfc',
    glowColor: 'rgba(240, 171, 252, 0.12)',
    shape: 'sphere',
    description: 'Modern teknolojilerle ölçeklenebilir, güvenli ve yüksek performanslı yazılım çözümleri geliştiriyoruz.',
    overview: [
      {
        h2: 'Hazır çözüm mü, özel yazılım mı?',
        body: 'Bu kararın tek doğru cevabı yoktur ve dürüst bir değerlendirme para kazandırır. Süreciniz sektörünüzdeki diğer şirketlerden çok farklı değilse, hazır bir ürün (ERP, muhasebe programı, hazır e-ticaret altyapısı) çok daha hızlı ve ucuzdur. Özel yazılım; iş akışınız rekabet avantajınızın parçasıysa, hazır ürünlerin zorladığı çalışma biçimi size sürekli maliyet çıkarıyorsa veya birden fazla sistemi birbirine bağlamanız gerekiyorsa mantıklı hale gelir. Kabaca ölçüt şudur: hazır üründe her ay yaptığınız manuel düzeltmelerin yıllık maliyeti, özel geliştirmenin maliyetine yaklaşıyorsa özel yazılım artık daha ucuzdur.',
      },
      {
        h2: 'Teknoloji seçimi ve uzun ömür',
        body: 'Bir yazılımın gerçek maliyeti yazıldığı gün değil, sonraki üç yılda ortaya çıkar. Bu yüzden teknoloji seçerken güncellik kadar sürdürülebilirliği gözetiyoruz: geniş topluluğa sahip, uzun süredir bakımı yapılan ve Türkiye\'de geliştirici bulunabilen teknolojiler tercih ediyoruz. Böylece bizimle çalışmaya devam etmeseniz bile projenizi devralacak birini bulabilirsiniz. Kod tabanının okunabilir olması, testlerin bulunması ve dokümantasyon bu devredilebilirliğin parçasıdır — bunlar \'lüks\' değil, satın aldığınız şeyin bir özelliğidir.',
      },
      {
        h2: 'Kodun sizin olması ve bağımlılık riski',
        body: 'Özel yazılım yaptırırken en kritik ama en az sorulan soru şudur: kod kime ait ve nerede duruyor? Teslim ettiğimiz projelerde kaynak kod sizindir ve kendi deponuza aktarılır. Sunucu erişimleri, alan adı ve üçüncü taraf hesapları sizin adınıza açılır. Bu, bizimle çalışmaya devam etmenizi tercihe dönüştürür, zorunluluğa değil. Ajans değiştirdiğinde sistemine erişemeyen çok sayıda işletme gördük; bu duruma düşmemek sözleşme aşamasında alınacak basit bir kararla mümkündür.',
      },
      {
        h2: 'Nasıl ilerliyoruz',
        body: 'Projeye tek seferde büyük bir teslimatla değil, çalışan parçalar halinde ilerliyoruz. Önce kapsamın en kritik çekirdeği tanımlanır ve kullanılabilir bir sürüm çıkarılır; siz gerçek veriyle denedikçe geri bildirim verirsiniz ve kapsam buna göre şekillenir. Bu yaklaşım, aylarca görülmeyen ve teslim gününde beklentiyi karşılamayan proje riskini büyük ölçüde ortadan kaldırır. Her aşamada ne yapıldığı ve ne kaldığı açıkça paylaşılır.',
      },
    ],
    faq: [
      { question: 'Özel yazılım projesi ne kadar sürer?', answer: 'Kapsama göre değişir. Tek bir işi çözen odaklı bir panel veya iç araç 4-8 hafta içinde kullanılabilir hale gelebilir. Birden fazla rolü, raporlamayı ve dış sistem entegrasyonlarını kapsayan iş uygulamaları 3-6 ay sürer. Süreyi en çok uzatan etken teknik zorluk değil, kapsamın proje sırasında sürekli değişmesidir; bu yüzden ilk aşamada kapsamı net yazıya dökmeye önem veriyoruz.' },
      { question: 'Yazılım bittikten sonra bakım gerekir mi?', answer: 'Evet, ve bu bir kusur değil normaldir. Kullandığınız kütüphaneler güvenlik güncellemesi alır, tarayıcılar ve işletim sistemleri değişir, iş ihtiyacınız gelişir. Bakımsız bırakılan bir yazılım iki-üç yıl içinde güvenlik açığı taşıyan ve güncellenmesi pahalı bir yapıya dönüşür. Düzenli küçük güncellemeler, birikmiş büyük bir yenileme projesinden çok daha ucuzdur.' },
      { question: 'Mevcut yazılımımız geliştirilebilir mi, sıfırdan mı yazılmalı?', answer: 'Önce mevcut kodu inceleyip dürüst bir değerlendirme yapıyoruz. Kod okunabilir ve mimari makulse, sıfırdan yazmak yerine iyileştirerek ilerlemek neredeyse her zaman daha ucuzdur. Sıfırdan yazmayı yalnızca teknoloji desteği tamamen bitmişse, güvenlik açıkları yapısalsa veya her küçük değişiklik orantısız maliyet çıkarıyorsa öneriyoruz. \'Baştan yazalım\' varsayılan cevabımız değildir.' },
      { question: 'Proje sırasında kapsam değişirse ne oluyor?', answer: 'Değişiklik normaldir ve süreç buna göre kurgulanır. Küçük düzenlemeler mevcut plan içinde karşılanır; süreyi veya maliyeti etkileyen değişikliklerde etkisini önceden paylaşıp onayınızı alırız. Amaç sürprizi ortadan kaldırmaktır: proje sonunda beklenmedik bir fatura veya beklenmedik bir eksik olmasın.' },
      { question: 'Yazılımın kaynak kodu bize ait olacak mı?', answer: 'Evet. Teslimde kaynak kod size devredilir ve kendi kod deponuza aktarılır. Sunucu, alan adı ve üçüncü taraf servis hesapları sizin adınıza açılır. Böylece ilerleyen dönemde çalışacağınız ekibi özgürce seçebilirsiniz.' },
    ],
    subServices: [
      {
        title: 'Web Yazılım',
        slug: 'web-yazilim',
        image: '🌐', icon: 'globe',
        description: 'Modern web teknolojileriyle hızlı, güvenli ve SEO uyumlu web uygulamaları geliştiriyoruz.',
        longDescription: 'React, Next.js, Vue.js ve Node.js gibi endüstri lideri teknolojilerle kurumsal düzeyde web uygulamaları geliştiriyoruz. Server-side rendering, static site generation ve edge computing ile maksimum performans sağlarken, SEO uyumlu yapı ile organik görünürlüğünüzü artırıyoruz.',
        features: ['React / Next.js / Vue.js', 'Node.js, Express & NestJS', 'PostgreSQL, MongoDB & Redis', 'CI/CD pipeline & DevOps', 'Server-side rendering (SSR)', 'Progressive Web App (PWA)'],
        process: ['Gereksinim analizi ve teknoloji seçimi', 'UI/UX tasarımı ve prototipleme', 'Agile geliştirme ve sprint döngüleri', 'Test, deployment ve bakım süreci'],
        // '%99.9 uptime garantili' ve 'Lighthouse 90+' ölçülmeyen GARANTİLERDİ (bulgu A-07).
        benefits: ['İzlenen, yedekli barındırma altyapısı', 'Core Web Vitals ölçütlerine göre optimize edilmiş teslim', 'Ölçeklenebilir, bakımı kolay mimari'],
        stats: [{ value: 'Next.js', label: 'Modern Altyapı' }, { value: 'Hız Odaklı', label: 'Core Web Vitals' }, { value: 'SEO', label: 'Arama Motoru Uyumu' }, { value: 'Responsive', label: 'Tüm Ekran Boyutları' }],
        faq: [
          { question: 'Web uygulama geliştirme süreci nasıl işler?', answer: 'Agile metodoloji ile çalışıyoruz. Gereksinim analizi, tasarım, geliştirme, test ve deployment aşamalarını 2 haftalık sprint döngülerinde iteratif olarak yürütüyoruz.' },
          { question: 'Hangi teknolojileri kullanıyorsunuz?', answer: 'Frontend için React, Next.js ve Vue.js; backend için Node.js, NestJS ve Express; veritabanı için PostgreSQL, MongoDB ve Redis kullanıyoruz. Projenin ihtiyaçlarına göre en uygun stack\'i seçiyoruz.' },
          { question: 'SEO uyumlu web sitesi nasıl yapılır?', answer: 'Server-side rendering (SSR), semantik HTML yapısı, Core Web Vitals optimizasyonu, structured data markup ve hızlı yükleme süreleri ile SEO uyumlu web siteleri geliştiriyoruz.' },
          { question: 'Bakım ve destek hizmeti sunuyor musunuz?', answer: 'Evet. Projenin tesliminden sonra güvenlik güncellemeleri, performans izleme, hata düzeltme ve yeni özellik geliştirme kapsamında sürekli bakım ve destek hizmeti sunuyoruz.' },
        ],
        metaTitle: 'Web Yazılım Geliştirme | React, Next.js | BERACORE',
        metaDescription: 'Modern web teknolojileriyle kurumsal web uygulamaları geliştirme. React, Next.js, Node.js, SEO uyumlu, yüksek performanslı. BERACORE web yazılım hizmetleri.',
      },
      {
        title: 'Mobil Uygulama',
        slug: 'mobil-uygulama',
        image: '📱', icon: 'mobile',
        description: 'iOS ve Android için native ve cross-platform mobil uygulamalar geliştiriyoruz.',
        longDescription: 'React Native ve Flutter ile tek kod tabanından iOS ve Android platformlarında çalışan yüksek performanslı mobil uygulamalar geliştiriyoruz. Native modül desteği ile platform özelliklerinin tamamından yararlanırken, geliştirme süresini ve maliyetini yarıya indiriyoruz.',
        features: ['React Native / Flutter', 'Native iOS (Swift) & Android (Kotlin)', 'Push bildirimler & deep linking', 'Offline mod & veri senkronizasyonu', 'Biyometrik kimlik doğrulama', 'App Store & Play Store optimizasyonu'],
        process: ['Kullanıcı araştırması ve UX tasarımı', 'Cross-platform veya native geliştirme', 'Beta test ve kullanıcı geri bildirimi', 'Store yayın ve performans izleme'],
        benefits: ['Tek kod tabanı ile %50 maliyet tasarrufu', 'Her iki platformda native performans', 'Hızlı time-to-market ve iterasyon'],
        stats: [{ value: 'iOS · Android', label: 'Çift Platform' }, { value: 'Tek Kod', label: 'Ortak Kod Tabanı' }, { value: 'Mağaza', label: 'Yayın Süreci Dahil' }, { value: 'Push', label: 'Bildirim Altyapısı' }],
        faq: [
          { question: 'Native ve cross-platform arasındaki fark nedir?', answer: 'Native uygulama her platform için ayrı kod yazılmasını gerektirirken, cross-platform (React Native/Flutter) tek kod tabanıyla her iki platformda çalışır. Cross-platform %50 maliyet tasarrufu sağlarken, native ise maksimum performans sunar.' },
          { question: 'Mobil uygulama geliştirme maliyeti nedir?', answer: 'Maliyet, uygulamanın karmaşıklığına göre değişir. Basit uygulamalar için daha düşük bütçe yeterli olurken, kapsamlı enterprise uygulamalar daha fazla yatırım gerektirir. Detaylı fiyat için bizimle iletişime geçin.' },
          { question: 'Uygulama store\'lara yayınlamayı da yapıyor musunuz?', answer: 'Evet. App Store ve Google Play Store hesap yönetimi, ASO (App Store Optimization), uygulama yayınlama ve güncelleme süreçlerinin tamamını yönetiyoruz.' },
          { question: 'Mevcut web sistemimle entegre olabilir mi?', answer: 'Kesinlikle. Mevcut web uygulamanız, API\'leriniz ve backend altyapınızla tam uyumlu mobil uygulamalar geliştiriyoruz. Aynı veri tabanını ve iş mantığını paylaşabilir.' },
        ],
        metaTitle: 'Mobil Uygulama Geliştirme | iOS & Android | BERACORE',
        metaDescription: 'iOS ve Android mobil uygulama geliştirme. React Native, Flutter, Swift & Kotlin. Cross-platform ile %50 maliyet tasarrufu. BERACORE mobil geliştirme.',
      },
      {
        title: 'Özel Yazılım',
        slug: 'ozel-yazilim',
        image: '🛠️', icon: 'wrench',
        description: 'İşletmenizin benzersiz ihtiyaçlarına özel yazılım çözümleri tasarlıyor ve geliştiriyoruz.',
        longDescription: 'ERP, CRM, iş zekası ve sektöre özel yazılım çözümlerini microservice mimarisi ile tasarlıyoruz. Mevcut sistemlerinizle tam entegre çalışan, işletmenizin büyümesiyle ölçeklenen özel yazılımlar geliştiriyoruz.',
        features: ['Kurumsal ERP sistemleri', 'Özel CRM çözümleri', 'İş zekası (BI) & raporlama', 'Microservice mimari', 'Event-driven & message queue', 'Kubernetes & Docker containerization'],
        process: ['İş süreçleri analizi ve çözüm tasarımı', 'Mimari tasarım ve teknoloji stack belirleme', 'Modüler geliştirme ve entegrasyon', 'Eğitim, deployment ve destek'],
        benefits: ['İş süreçlerine tam uyumlu özel çözümler', 'Sınırsız ölçeklenebilirlik ve esneklik', 'Tam sahiplik ve bağımsızlık'],
        stats: [{ value: 'Agile', label: 'Çalışma Modeli' }, { value: 'Kaynak Kod', label: 'Tam Sahiplik Sizde' }, { value: 'Modüler', label: 'Ölçeklenebilir Mimari' }, { value: 'Dokümante', label: 'Devir Teslim Belgeleri' }],
        faq: [
          { question: 'Özel yazılım ne zaman tercih edilmelidir?', answer: 'Hazır çözümler iş süreçlerinize uyum sağlayamadığında, benzersiz ihtiyaçlarınız olduğunda veya rekabet avantajı elde etmek istediğinizde özel yazılım doğru tercihdir.' },
          { question: 'Microservice mimari neden önemlidir?', answer: 'Microservice mimari, uygulamanızı bağımsız modüllere bölerek her birini ayrı ölçeklendirmenizi, güncellemenizi ve dağıtmanızı sağlar. Sistem dayanıklılığını artırır ve ekip verimliliğini yükseltir.' },
          { question: 'Mevcut sistemlerimiz korunabilir mi?', answer: 'Evet. Legacy sistemlerinizi modernize ederken mevcut veri ve iş süreçlerinizi koruyoruz. Kademeli geçiş stratejisi ile iş sürekliliğini kesintiye uğratmadan yeni sisteme geçiş sağlarız.' },
          { question: 'Kaynak kodun sahipliği kime aittir?', answer: 'Kaynak kodun tam sahipliği size aittir. Proje tesliminde tüm kaynak kod, dokümantasyon ve erişim bilgileri eksiksiz olarak teslim edilir.' },
        ],
        metaTitle: 'Özel Yazılım Geliştirme | ERP, CRM | BERACORE',
        metaDescription: 'İşletmenize özel yazılım çözümleri. ERP, CRM, iş zekası, microservice mimari. Ölçeklenebilir ve tam özelleştirilebilir kurumsal yazılım geliştirme. BERACORE.',
      },
      {
        title: 'API & Entegrasyon',
        slug: 'api-entegrasyon',
        image: '🔌', icon: 'plug',
        description: 'Sistemlerinizi birbirine bağlayan güçlü API\'ler ve entegrasyonlar geliştiriyoruz.',
        longDescription: 'RESTful, GraphQL ve gRPC protokolleri ile yüksek performanslı API\'ler tasarlıyor ve geliştiriyoruz. Mevcut sistemlerinizi, üçüncü parti hizmetleri ve iş ortaklarınızın platformlarını sorunsuz şekilde birbirine bağlıyoruz.',
        features: ['RESTful API tasarımı & geliştirme', 'GraphQL & gRPC implementasyonu', '3. parti entegrasyon (SAP, Salesforce vb.)', 'Webhook & event-driven mimari', 'API gateway & rate limiting', 'Swagger/OpenAPI dokümantasyon'],
        process: ['API spesifikasyonu ve kontrat tasarımı', 'Endpoint geliştirme ve güvenlik katmanı', 'Entegrasyon testi ve yük testi', 'Dokümantasyon ve developer portal'],
        benefits: ['Tüm sistemleriniz tek bir platformda birleşir', 'Yüksek güvenlikli ve performanslı API\'ler', 'Kapsamlı dokümantasyon ve SDK desteği'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'RESTful API ve GraphQL arasındaki fark nedir?', answer: 'REST, kaynağa dayalı sabit endpoint\'ler sunarken, GraphQL tek endpoint üzerinden istemcinin tam olarak ihtiyaç duyduğu veriyi sorgulamasını sağlar. GraphQL over-fetching ve under-fetching problemlerini çözer.' },
          { question: 'API güvenliği nasıl sağlanır?', answer: 'OAuth 2.0, JWT token, API key, rate limiting, IP whitelisting ve SSL/TLS şifreleme ile API\'lerinizi koruyoruz. OWASP API Security standartlarına uygun geliştirme yapıyoruz.' },
          { question: 'Hangi üçüncü parti sistemlerle entegrasyon yapabilirsiniz?', answer: 'SAP, Salesforce, HubSpot, Stripe, PayPal, Google, Meta, AWS servisleri ve daha 50+ platformla entegrasyon yapabiliyoruz. İhtiyacınıza özel entegrasyonlar da geliştiriyoruz.' },
          { question: 'API dokümantasyonu nasıl oluşturulur?', answer: 'OpenAPI/Swagger standardında interaktif API dokümantasyonu oluşturuyoruz. Developer portal ile geliştiricileriniz API\'leri kolayca test edebilir ve entegre edebilir.' },
        ],
        metaTitle: 'API Geliştirme & Sistem Entegrasyonu | BERACORE',
        metaDescription: 'RESTful API, GraphQL ve sistem entegrasyonu hizmetleri. SAP, Salesforce, 3. parti entegrasyonlar. Yüksek performanslı API geliştirme. BERACORE.',
      },
    ],
  },
  {
    key: 'design',
    title: 'Tasarım',
    subtitle: 'Estetik kod ile buluşuyor',
    color: '#fda4af',
    glowColor: 'rgba(253, 164, 175, 0.12)',
    shape: 'diamond',
    description: 'Kullanıcı odaklı tasarım anlayışıyla markanızın dijital yüzünü kusursuz şekilde oluşturuyoruz.',
    overview: [
      {
        h2: 'İyi tasarım güzel görünmekten fazlasıdır',
        body: 'Bir arayüzün başarısı, beğenilmesiyle değil kullanıcının amacına ne kadar hızlı ulaştığıyla ölçülür. Ziyaretçi ne yapacağını anlayamıyorsa, form fazla uzun geliyorsa veya mobilde butona ulaşmak zorsa, tasarım ne kadar estetik olursa olsun iş sonucunu düşürür. Bu yüzden tasarım sürecine görselden değil, kullanıcının izlediği yoldan başlıyoruz: kim geliyor, ne arıyor, hangi adımda vazgeçiyor. Görsel dil bu iskeletin üzerine kurulur; tersi sıralama, güzel ama işlevsiz sayfalar üretir.',
      },
      {
        h2: 'Marka kimliği tek bir logodan ibaret değildir',
        body: 'Logo, marka kimliğinin yalnızca en görünür parçasıdır. Kimliği asıl taşıyan şey tutarlılıktır: aynı renk paleti, aynı tipografi ölçeği, aynı ton ve aynı boşluk mantığı her temas noktasında tekrar ettiğinde marka tanınır hale gelir. Bu nedenle kimlik çalışmalarında logonun yanında kullanım kuralları, renk ve tipografi sistemi, sosyal medya ve basılı uygulama şablonları da teslim edilir. Kurallar olmadan verilen bir logo, birkaç ay içinde her yerde farklı görünen bir markaya dönüşür.',
      },
      {
        h2: 'Erişilebilirlik bir ek özellik değil',
        body: 'Yeterli renk kontrastı, klavyeyle kullanılabilirlik, ekran okuyucuya anlamlı gelen yapı ve dokunma hedeflerinin parmakla kullanılabilecek büyüklükte olması — bunlar azınlık için yapılan iyilikler değil, herkes için daha iyi arayüzler üretir. Güneş altında telefonuna bakan bir kullanıcı da düşük kontrastta zorlanır. Tasarımlarımızı WCAG AA ölçütlerine göre kuruyor ve teslim öncesi gerçek tarayıcıda ölçüyoruz; bu ölçüm tahmine bırakılmaz.',
      },
      {
        h2: 'Tasarımdan koda geçiş',
        body: 'Birçok projede kayıp, tasarımın koda dönüştüğü aşamada yaşanır: yazı tipleri kayar, boşluklar bozulur, mobilde beklenmedik taşmalar çıkar. Tasarım ve geliştirmeyi aynı ekip içinde yürüttüğümüz için bu kopukluğu baştan ortadan kaldırıyoruz. Tasarım dosyası bir resim değil, doğrudan koda karşılık gelen bir sistem olarak kurulur: renk ve ölçü değişkenleri, bileşen mantığı ve durum tanımları. Sonuç, ekranda gördüğünüzün tarayıcıda da aynısı olmasıdır.',
      },
    ],
    faq: [
      { question: 'Web tasarım projesi ne kadar sürer?', answer: 'Kurumsal tanıtım siteleri genellikle 3-6 hafta içinde tamamlanır. Çok sayfalı, özel içerik yapısı olan veya e-ticaret içeren projeler 6-12 haftaya uzayabilir. Süreyi en çok etkileyen unsur tasarım değil, içeriktir: metinler ve görseller hazırsa süreç belirgin biçimde kısalır.' },
      { question: 'Hazır tema mı, özel tasarım mı?', answer: 'Bütçe sınırlıysa ve amaç hızlıca görünür olmaksa hazır tema makul bir başlangıçtır. Ancak hazır temalar genellikle ihtiyaç duymadığınız çok sayıda özelliği de yükler; bu da yavaş sayfa ve zayıf Core Web Vitals anlamına gelir. Markanızın ayırt edici görünmesi, sayfa hızının rekabet konusu olduğu bir sektörde çalışmanız veya standart dışı bir içerik yapınız varsa özel tasarım uzun vadede daha iyi sonuç verir.' },
      { question: 'Tasarım sürecinde kaç revizyon hakkımız var?', answer: 'Çalışma biçimimiz sabit bir revizyon sayısı saymak üzerine kurulu değil. Süreci aşamalara bölüyoruz: önce yapı ve akış onaylanır, sonra görsel dil, en son detaylar. Her aşama onaylandıktan sonra bir sonrakine geçildiği için, projenin sonunda baştan başlamayı gerektiren büyük değişiklikler nadiren gerekir.' },
      { question: 'Mobil uyumluluk dahil mi?', answer: 'Evet, ve sonradan eklenen bir katman olarak değil. Tasarım küçük ekran öncelikli kurulur, sonra büyük ekranlara genişletilir. Teslim öncesi 320 pikselden 1920 piksele kadar gerçek tarayıcıda kontrol edilir; taşma, kesilen buton veya okunamayan metin kalmadığı ölçümle doğrulanır.' },
      { question: 'Logo tasarımında bize ne teslim ediliyor?', answer: 'Logonun yatay, dikey ve simge varyasyonları; baskı ve dijital için uygun dosya formatları (vektör dahil); renk kodları; tipografi seçimleri ve kullanım kuralları. Vektör dosyanın teslim edilmesi önemlidir — onsuz logonuzu büyük ölçekte kullanamazsınız.' },
    ],
    subServices: [
      {
        title: 'Web Tasarım', slug: 'web-tasarim', image: '🎨', icon: 'palette',
        description: 'Markanızı dijitalde en iyi şekilde temsil eden, modern ve responsive web tasarımları oluşturuyoruz.',
        longDescription: 'Piksel mükemmelliğinde, responsive ve erişilebilir web tasarımları oluşturuyoruz. Motion design ve micro-interaction\'lar ile kullanıcı deneyimini zenginleştirirken, markanızın dijital kimliğini güçlendiriyoruz. Figma\'da detaylı prototipler hazırlayarak geliştirme sürecini hızlandırıyoruz.',
        features: ['Responsive & mobile-first tasarım', 'Motion design & micro-interaction', 'Figma & Adobe XD prototyping', 'Design system oluşturma', 'Dark/light mode tasarımı', 'Accessibility (WCAG 2.1 AA)'],
        process: ['Marka analizi ve moodboard oluşturma', 'Wireframe ve bilgi mimarisi tasarımı', 'Yüksek sadakatli UI tasarımı', 'Prototip testi ve geliştirme handoff'],
        benefits: ['Marka kimliğiyle tam uyumlu dijital deneyim', 'Dönüşüm oranlarında ortalama %35 artış', 'Tüm cihazlarda kusursuz görünüm'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'Web tasarım süreci nasıl işler?', answer: 'Marka analiziyle başlayıp, wireframe, UI tasarımı ve prototipleme aşamalarından geçerek geliştirme ekibine handoff ile tamamlanır. Her aşamada sizin onayınız alınır.' },
          { question: 'Responsive tasarım nedir?', answer: 'Responsive tasarım, web sitenizin masaüstü, tablet ve mobil dahil her ekran boyutunda optimum görünüm ve kullanım deneyimi sunmasını sağlayan tasarım yaklaşımıdır.' },
          { question: 'Design system neden önemlidir?', answer: 'Design system, tutarlı görsel dil, yeniden kullanılabilir bileşenler ve tasarım kuralları sağlayarak geliştirme hızını artırır ve marka tutarlılığını garanti eder.' },
          { question: 'Tasarım revizyon hakkı var mıdır?', answer: 'Evet. Her proje kapsamında belirlenen sayıda revizyon hakkı sunuyoruz. Tasarım sürecinde düzenli feedback döngüleri ile beklentilerinize tam uyum sağlarız.' },
        ],
        metaTitle: 'Profesyonel Web Tasarım Hizmetleri | BERACORE',
        metaDescription: 'Modern, responsive ve SEO uyumlu web tasarım hizmetleri. Figma prototyping, motion design, design system. Dönüşüm odaklı web tasarım ajansı BERACORE.',
      },
      {
        title: 'UI/UX Tasarım', slug: 'ui-ux-tasarim', image: '✨', icon: 'layout',
        description: 'Kullanıcı araştırması ve testleriyle desteklenen, dönüşüm odaklı arayüz ve deneyim tasarımları.',
        longDescription: 'Veri odaklı kullanıcı araştırması, persona oluşturma ve journey mapping ile başlayan kapsamlı UX süreçleri yürütüyoruz. A/B test tasarımları ve kullanılabilirlik testleri ile her tasarım kararını veriyle destekliyoruz.',
        features: ['Kullanıcı araştırması & persona', 'User journey & flow mapping', 'Wireframe & interaktif prototip', 'A/B test tasarımı & analiz', 'Accessibility denetimi (WCAG)', 'Heuristic & usability evaluation'],
        process: ['Kullanıcı araştırması ve içgörü analizi', 'Bilgi mimarisi ve wireframe tasarımı', 'İnteraktif prototip ve kullanıcı testi', 'İterasyon ve final tasarım teslimi'],
        benefits: ['Veriye dayalı, kanıtlanmış tasarım kararları', 'Kullanıcı memnuniyetinde ölçülebilir artış', 'Düşük bounce rate ve yüksek dönüşüm'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'UI ve UX arasındaki fark nedir?', answer: 'UI (User Interface) görsel arayüz tasarımıdır: renkler, tipografi, butonlar. UX (User Experience) ise kullanıcı deneyiminin tamamını kapsar: kullanılabilirlik, erişilebilirlik, kullanıcı akışları ve memnuniyet.' },
          { question: 'Kullanıcı araştırması neden gereklidir?', answer: 'Kullanıcı araştırması, hedef kitlenizin gerçek ihtiyaçlarını, davranışlarını ve beklentilerini anlamanızı sağlar. Varsayımlara değil, verilere dayalı tasarım kararları alarak başarısızlık riskini minimuma indirir.' },
          { question: 'A/B testi nasıl yapılır?', answer: 'İki farklı tasarım varyasyonunu gerçek kullanıcılara göstererek hangisinin daha iyi performans gösterdiğini ölçeriz. Dönüşüm oranı, tıklama oranı ve kullanıcı davranışı metrikleri ile değerlendiririz.' },
          { question: 'Mevcut ürünüm için UX iyileştirme yapabilir misiniz?', answer: 'Evet. Mevcut ürününüz için heuristic değerlendirme, kullanılabilirlik testi ve veri analizi yaparak iyileştirme önerileri sunuyor ve uyguluyoruz.' },
        ],
        metaTitle: 'UI/UX Tasarım Hizmetleri | BERACORE',
        metaDescription: 'Kullanıcı araştırması, wireframe, prototipleme ve A/B test ile dönüşüm odaklı UI/UX tasarım. Kullanıcı deneyimi tasarım ajansı BERACORE.',
      },
      {
        title: 'Marka Kimliği', slug: 'marka-kimligi', image: '🏷️', icon: 'badge',
        description: 'Logo, renk paleti, tipografi ve marka rehberinden oluşan kapsamlı marka kimliği paketleri.',
        longDescription: 'Stratejik marka konumlandırmasından görsel kimlik tasarımına kadar bütünsel bir marka oluşturma süreci sunuyoruz. Logo, renk sistemi, tipografi ve görsel dil tanımını içeren kapsamlı marka rehberleri hazırlıyoruz.',
        features: ['Stratejik logo tasarımı', 'Renk sistemi & tipografi', 'Kapsamlı marka rehberi (brand book)', 'Sosyal medya kiti & şablonlar', 'Kurumsal kimlik uygulamaları', 'İkon & illüstrasyon seti'],
        process: ['Marka stratejisi ve konumlandırma workshop\'u', 'Görsel kimlik araştırması ve konsept geliştirme', 'Logo ve kimlik elemanları tasarımı', 'Brand book ve uygulama kılavuzu teslimi'],
        benefits: ['Rakiplerden farklılaşan güçlü marka algısı', 'Tüm temas noktalarında tutarlı kimlik', 'Profesyonel, ölçeklenebilir marka sistemi'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'Marka kimliği tasarımı neleri kapsar?', answer: 'Logo, renk paleti, tipografi, ikonlar, görsel dil kuralları, kurumsal kimlik uygulamaları (kartvizit, antetli kağıt vb.) ve sosyal medya kitini kapsayan bütünsel bir pakettir.' },
          { question: 'Logo tasarımı süreci nasıl işler?', answer: 'Marka stratejisi workshop\'u ile başlıyoruz. Araştırma, konsept geliştirme, tasarım alternatifleri ve revizyonlar ile final logonuza ulaşıyoruz. Genellikle 3-4 hafta sürer.' },
          { question: 'Brand book (marka rehberi) nedir?', answer: 'Brand book, markanızın görsel ve sözel kimliğinin nasıl kullanılacağını tanımlayan kapsamlı bir kılavuzdur. Logo kullanım kuralları, renk kodları, tipografi, ton ve ses gibi tüm standartları içerir.' },
          { question: 'Mevcut markamı yenileyebilir misiniz?', answer: 'Evet. Rebranding hizmeti ile mevcut marka kimliğinizi modernize ediyor, marka değerinizi koruyarak güncelleştiriyoruz.' },
        ],
        metaTitle: 'Marka Kimliği Tasarımı | Logo & Brand Book | BERACORE',
        metaDescription: 'Profesyonel marka kimliği tasarımı. Logo, renk sistemi, tipografi, brand book, sosyal medya kiti. Stratejik marka konumlandırma. BERACORE tasarım ajansı.',
      },
      {
        title: 'Grafik Tasarım', slug: 'grafik-tasarim', image: '🖼️', icon: 'frame',
        description: 'Dijital ve basılı ortamlar için etkileyici görsel tasarımlar üretiyoruz.',
        longDescription: 'Sosyal medya görselleri, banner reklamlar, infografikler, sunum tasarımları ve basılı materyaller gibi geniş bir yelpazede profesyonel grafik tasarım hizmeti sunuyoruz. Marka kimliğinizle uyumlu, dikkat çekici ve mesajınızı etkili şekilde ileten görseller üretiyoruz.',
        features: ['Sosyal medya görsel tasarımı', 'Banner & display reklam tasarımı', 'Kurumsal sunum tasarımı', 'İnfografik & veri görselleştirme', 'Baskı & ambalaj tasarımı', 'Motion graphics & kısa video'],
        process: ['Brief analizi ve yaratıcı konsept', 'Tasarım alternatifleri ve revizyon', 'Final tasarım ve dosya hazırlığı', 'Çoklu format export ve teslim'],
        benefits: ['Marka ile uyumlu, tutarlı görsel dil', 'Sosyal medyada artan etkileşim ve görünürlük', 'Print-ready ve dijital-ready profesyonel çıktılar'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'Hangi grafik tasarım hizmetlerini sunuyorsunuz?', answer: 'Sosyal medya görselleri, banner reklamlar, infografikler, sunum tasarımı, kartvizit, broşür, poster, ambalaj tasarımı ve motion graphics dahil geniş bir yelpazede hizmet sunuyoruz.' },
          { question: 'Tasarım dosyaları hangi formatta teslim edilir?', answer: 'PNG, JPG, SVG, PDF, AI, PSD ve FIGMA formatlarında teslim ediyoruz. Baskı için CMYK, dijital için RGB renk modunda hazırlanır.' },
          { question: 'Toplu tasarım paketleri var mı?', answer: 'Evet. Aylık sosyal medya tasarım paketleri, reklam kampanyası paketleri ve kurumsal tasarım abonelikleri sunuyoruz. İhtiyacınıza göre özel paket oluşturabiliriz.' },
          { question: 'Tasarım süreciniz ne kadar sürer?', answer: 'Tekil tasarımlar 24-48 saat, kapsamlı projeler 1-2 hafta içinde teslim edilir. Acil projeler için ekspres hizmet seçeneğimiz mevcuttur.' },
        ],
        metaTitle: 'Profesyonel Grafik Tasarım Hizmetleri | BERACORE',
        metaDescription: 'Sosyal medya görselleri, banner, infografik, sunum ve baskı tasarımı. Marka uyumlu profesyonel grafik tasarım hizmetleri. BERACORE tasarım ajansı.',
      },
    ],
  },
  {
    key: 'ecommerce',
    title: 'E-Ticaret',
    subtitle: 'Satışın dijital gücü',
    color: '#6ee7b7',
    glowColor: 'rgba(110, 231, 183, 0.12)',
    shape: 'torus',
    description: 'Satışlarınızı artıran, operasyonlarınızı kolaylaştıran güçlü e-ticaret platformları kuruyoruz.',
    overview: [
      {
        h2: 'Doğru e-ticaret altyapısını seçmek',
        body: 'E-ticarette en pahalı hata, yanlış altyapıyla başlayıp bir yıl sonra taşınmak zorunda kalmaktır. Kiralık paket sistemler hızlı başlangıç ve düşük giriş maliyeti sunar; buna karşılık özelleştirme sınırlıdır ve ciro arttıkça komisyon/abonelik yükü büyür. Açık kaynak altyapılar daha esnektir ama bakım sorumluluğu sizdedir. Özel geliştirme, standart dışı bir satış modeliniz veya yoğun entegrasyon ihtiyacınız varsa anlam kazanır. Karar verirken bugünkü ürün sayınıza değil, iki yıl sonraki hedefinize ve mevcut sistemlerinizle kurmanız gereken bağlantılara bakmanızı öneririz.',
      },
      {
        h2: 'Dönüşüm oranı, trafikten daha ucuzdur',
        body: 'Çoğu e-ticaret sitesinde en hızlı kazanç yeni ziyaretçi almaktan değil, gelen ziyaretçinin daha fazlasını müşteriye çevirmekten gelir. Sepeti terk ettiren nedenler genellikle tahmin edilebilir: beklenmedik kargo ücreti, zorunlu üyelik, uzun form, güven vermeyen ödeme adımı, mobilde zor kullanılan arayüz ve yavaş açılan sayfalar. Bunların her biri ölçülebilir ve düzeltilebilir. Reklam bütçesini artırmadan önce bu adımların gözden geçirilmesi, aynı trafikten belirgin biçimde daha fazla sipariş çıkarır.',
      },
      {
        h2: 'Pazaryeri ve kendi siteniz birlikte çalışmalı',
        body: 'Trendyol, Hepsiburada, N11 ve Amazon hazır müşteri kitlesine erişim sağlar; ancak müşteri ilişkisi ve marj büyük ölçüde platformda kalır. Kendi siteniz ise marjı ve müşteri verisini size bırakır, karşılığında trafiği kendiniz üretmeniz gerekir. Sağlıklı kurgu ikisini birlikte kullanmaktır: pazaryerleri hacim ve bilinirlik, kendi siteniz kârlılık ve tekrar satış. Bunun işleyebilmesi için stok ve fiyatın tek merkezden yönetilmesi şarttır; aksi halde aşırı satış ve iptal sorunları hızla büyür.',
      },
      {
        h2: 'Entegrasyonlar operasyonu belirler',
        body: 'E-ticaretin görünmeyen ama en belirleyici tarafı entegrasyonlardır: muhasebe ve e-fatura, kargo firmaları, ödeme altyapısı, stok yönetimi ve pazaryeri bağlantıları. Bu halkalardan biri elle yürüdüğünde sipariş sayısı arttıkça operasyon tıkanır ve hata oranı yükselir. Kurduğumuz sistemlerde bu akışların otomatik ve birbiriyle tutarlı çalışmasına öncelik veriyoruz; çünkü büyümenin önündeki engel çoğu zaman satış değil, operasyondur.',
      },
    ],
    faq: [
      { question: 'E-ticaret sitesi kurmak ne kadar sürer?', answer: 'Hazır altyapı üzerine kurulan, standart ödeme ve kargo entegrasyonları olan bir mağaza 3-6 haftada satışa açılabilir. Özel tasarım, ERP entegrasyonu veya pazaryeri bağlantıları içeren projeler 2-4 ay sürer. Ürün görselleri ve açıklamalarının hazır olması süreci belirgin şekilde hızlandırır.' },
      { question: 'Sanal POS almak için neler gerekir?', answer: 'Banka veya ödeme kuruluşuyla anlaşma, şirket belgeleri, alan adının şirketiniz adına olması ve sitede mesafeli satış sözleşmesi, iade/iptal koşulları, teslimat bilgileri ile iletişim bilgilerinin eksiksiz yayınlanmış olması gerekir. Ödeme kuruluşları başvuru sırasında bu sayfaları kontrol eder; eksikse başvuru reddedilir. Teknik entegrasyonu biz üstleniyoruz.' },
      { question: 'Pazaryerinde mi satmalıyım, kendi sitemde mi?', answer: 'İkisi rakip değil tamamlayıcıdır. Pazaryeri hazır trafik ve hızlı başlangıç sağlar, kendi siteniz daha yüksek marj ve müşteri verisi bırakır. Yeni markalar için yaygın ve mantıklı sıralama, pazaryerinde hacim ve deneyim kazanıp kendi sitesini paralel büyütmektir. Kritik nokta stok ve fiyatı tek yerden yönetmektir.' },
      { question: 'Mevcut mağazamı taşırsam SEO\'m zarar görür mü?', answer: 'Doğru yapılmazsa ciddi biçimde görebilir. Taşıma sırasında eski URL\'lerin yenilerine kalıcı yönlendirme (301) ile bağlanması, ürün ve kategori adreslerinin korunması, sayfa başlıkları ile açıklamaların taşınması ve site haritasının güncellenmesi gerekir. Bu adımlar planlanarak yapıldığında sıralama kaybı genellikle geçici ve sınırlı olur.' },
      { question: 'Kaç ürünle başlamalıyım?', answer: 'Ürün sayısından çok, ürün sayfalarının kalitesi belirleyicidir. Özgün açıklama, doğru görsel ve net teslimat bilgisi taşıyan az sayıda ürün; kopya açıklamalı yüzlerce üründen daha iyi sonuç verir. Arama motorları da kullanıcılar da bu farkı ayırt eder.' },
    ],
    subServices: [
      {
        title: 'E-Ticaret Yazılım', slug: 'e-ticaret-yazilim', image: '🛒', icon: 'cart',
        description: 'Özel e-ticaret platformları ve mağaza yazılımları geliştiriyoruz.',
        longDescription: 'Yüksek trafik altında stabil çalışan, ölçeklenebilir özel e-ticaret platformları geliştiriyoruz. Gelişmiş stok yönetimi, otomatik sipariş süreçleri, çoklu dil ve para birimi desteği ile uluslararası pazarlara açılın. Kişiselleştirilmiş alışveriş deneyimi ve akıllı öneri motoru ile dönüşüm oranlarınızı maksimize edin.',
        features: ['Özel mağaza yazılımı', 'Gelişmiş stok & sipariş yönetimi', 'Çoklu dil & para birimi desteği', 'Mobil uyumlu & PWA', 'Akıllı ürün öneri motoru', 'Gelişmiş arama & filtreleme'],
        process: ['E-ticaret stratejisi ve platform planlaması', 'UI/UX tasarımı ve geliştirme', 'Ödeme, kargo ve ERP entegrasyonları', 'Lansman, SEO optimizasyonu ve bakım'],
        benefits: ['Sınırsız özelleştirme ve ölçeklenebilirlik', 'Dönüşüm oranlarında ortalama %40 artış', 'Tam kontrol ve bağımsızlık'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'Özel e-ticaret yazılımı mı yoksa hazır çözüm mü tercih etmeliyim?', answer: 'Benzersiz iş süreçleriniz varsa, yüksek ölçeklenebilirlik istiyorsanız veya farklılaşmak istiyorsanız özel yazılım tercih edilmelidir. Standart ihtiyaçlar için hazır çözümler de değerlendirilebilir.' },
          { question: 'E-ticaret sitesi geliştirme ne kadar sürer?', answer: 'Temel bir e-ticaret sitesi 6-8 haftada, kapsamlı özel platformlar 3-6 ayda tamamlanır. MVP yaklaşımıyla erken çıkış yapıp kademeli olarak geliştirmek mümkündür.' },
          { question: 'Hangi ödeme ve kargo entegrasyonlarını destekliyorsunuz?', answer: 'iyzico, PayTR, Stripe, Garanti, Yapı Kredi sanal POS; Yurtiçi, Aras, MNG, UPS, DHL kargo; ve ERP entegrasyonları dahil 50+ entegrasyonu destekliyoruz.' },
          { question: 'SEO uyumlu e-ticaret sitesi nasıl olur?', answer: 'Temiz URL yapısı, hızlı yükleme, structured data (ürün schema), optimize görseller, canonical URL\'ler ve sitemap ile SEO uyumlu e-ticaret siteleri geliştiriyoruz.' },
        ],
        metaTitle: 'E-Ticaret Yazılım Geliştirme | Online Mağaza | BERACORE',
        metaDescription: 'Özel e-ticaret platformu ve online mağaza yazılımı geliştirme. Stok yönetimi, ödeme entegrasyonu, SEO uyumlu. Dönüşüm odaklı e-ticaret çözümleri. BERACORE.',
      },
      {
        title: 'Pazaryeri Entegrasyonu', slug: 'pazaryeri-entegrasyonu', image: '🏪', icon: 'store',
        description: 'Trendyol, Hepsiburada, Amazon ve diğer pazaryerlerine entegrasyon sağlıyoruz.',
        longDescription: 'Trendyol, Hepsiburada, Amazon, Etsy, N11 ve daha fazla pazaryerini tek bir panelden yönetin. Stok senkronizasyonu, otomatik fiyatlandırma, sipariş yönetimi ve performans raporlaması ile çoklu kanal satış stratejinizi güçlendiriyoruz.',
        features: ['Trendyol & Hepsiburada entegrasyonu', 'Amazon, Etsy & N11 desteği', 'Gerçek zamanlı stok senkronizasyonu', 'Otomatik & dinamik fiyatlandırma', 'Çoklu kanal sipariş yönetimi', 'Satış performansı raporlama'],
        process: ['Pazaryeri hesap ve API yapılandırması', 'Ürün kataloğu eşleştirme ve aktarım', 'Stok ve sipariş senkronizasyonu kurulumu', 'Canlıya alma ve sürekli izleme'],
        benefits: ['Tek panelden tüm pazaryerlerini yönetme', 'Stok tutarsızlığı riskinin ortadan kalkması', 'Satışlarda çoklu kanal ile %60 artış'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'Hangi pazaryerlerini destekliyorsunuz?', answer: 'Trendyol, Hepsiburada, N11, GittiGidiyor, Amazon, Etsy, Shopify ve daha 15+ pazaryerini destekliyoruz. Yeni pazaryerleri talep üzerine entegre edilir.' },
          { question: 'Stok senkronizasyonu nasıl çalışır?', answer: 'Gerçek zamanlı API entegrasyonu ile tüm kanallarınızdaki stok bilgileri otomatik olarak güncellenir. Bir kanalda satış gerçekleştiğinde diğer kanallardaki stok anında düşer.' },
          { question: 'Mevcut e-ticaret sitemle uyumlu mudur?', answer: 'Evet. Mevcut WooCommerce, Shopify, IdeaSoft veya özel e-ticaret altyapınızla tam uyumlu entegrasyonlar geliştiriyoruz.' },
          { question: 'Dinamik fiyatlandırma nasıl çalışır?', answer: 'Rakip fiyatlarını, talep trendlerini ve marj hedeflerinizi analiz ederek her pazaryeri için otomatik fiyat ayarlaması yapan akıllı fiyatlandırma kuralları oluşturuyoruz.' },
        ],
        metaTitle: 'Pazaryeri Entegrasyonu | Trendyol, Amazon | BERACORE',
        metaDescription: 'Trendyol, Hepsiburada, Amazon pazaryeri entegrasyonu. Stok senkronizasyonu, otomatik fiyatlandırma, çoklu kanal yönetimi. BERACORE e-ticaret çözümleri.',
      },
      {
        title: 'Ödeme Sistemleri', slug: 'odeme-sistemleri', image: '💎', icon: 'diamond',
        description: 'Güvenli ve hızlı ödeme entegrasyonları kuruyoruz.',
        longDescription: 'iyzico, Stripe, PayTR ve tüm popüler ödeme yöntemlerini destekleyen güvenli ödeme altyapıları kuruyoruz. Sanal POS entegrasyonu, taksitli ödeme seçenekleri, abonelik yönetimi ve tekrarlayan ödeme sistemleri ile her iş modeline uygun çözümler sunuyoruz.',
        features: ['iyzico, Stripe & PayTR entegrasyonu', 'Sanal POS & banka entegrasyonu', 'Taksitli ödeme seçenekleri', 'Abonelik & tekrarlayan ödeme', '3D Secure ve PCI DSS sertifikalı sağlayıcı entegrasyonu', 'Sahtekarlık tespit & önleme'],
        process: ['Ödeme ihtiyaçları analizi ve sağlayıcı seçimi', 'Ödeme gateway entegrasyonu ve test', 'Güvenlik denetimi ve sertifikasyon', 'Canlıya alma ve transaction monitoring'],
        benefits: ['Tüm popüler ödeme yöntemlerinin desteği', 'En yüksek düzeyde ödeme güvenliği', 'Sepet terk oranında %25 düşüş'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'Hangi ödeme yöntemlerini destekliyorsunuz?', answer: 'Kredi kartı, banka kartı, havale/EFT, BKM Express, Apple Pay, Google Pay, Masterpass ve kripto para dahil 20+ ödeme yöntemini destekliyoruz.' },
          { question: 'Taksitli ödeme nasıl entegre edilir?', answer: 'Sanal POS entegrasyonu ile tüm büyük bankaların taksit seçeneklerini otomatik olarak müşterilerinize sunuyoruz. Banka bazında taksit oranlarını yönetebilirsiniz.' },
          { question: 'Abonelik sistemi kurulabilir mi?', answer: 'Evet. Stripe ve iyzico altyapısı ile aylık/yıllık abonelik, freemium modeli ve tekrarlayan ödeme sistemleri kuruyoruz. Otomatik fatura oluşturma ve ödeme hatırlatma dahildir.' },
          { question: 'Ödeme güvenliği nasıl sağlanır?', answer: '3D Secure, tokenization ve sahtekârlık önleme ile ödemelerin güvenliğini sağlıyoruz. Kart verileri PCI DSS sertifikalı sağlayıcıda işlenir; sizin sisteminizde saklanmaz.' },
        ],
        metaTitle: 'Ödeme Sistemi Entegrasyonu | Sanal POS | BERACORE',
        metaDescription: 'iyzico, Stripe, sanal POS entegrasyonu ve güvenli ödeme çözümleri. Taksitli ödeme, abonelik, 3D Secure. E-ticaret ödeme sistemleri. BERACORE.',
      },
    ],
  },
  {
    key: 'marketing',
    title: 'Dijital Pazarlama',
    subtitle: 'Doğru kitleye, doğru zamanda',
    color: '#fde68a',
    glowColor: 'rgba(253, 230, 138, 0.12)',
    shape: 'ring',
    description: 'Veriye dayalı stratejilerle markanızı hedef kitlenize ulaştırıyor, sürdürülebilir büyüme sağlıyoruz.',
    overview: [
      {
        h2: 'Dijital pazarlamada gerçekçi beklenti',
        body: 'Bu alanda en büyük hayal kırıklığı, yanlış zaman beklentisinden doğar. SEO kalıcı ve maliyeti zamanla düşen bir kanaldır ama ilk anlamlı sonuçları genellikle 4-6 ayda verir; yeni bir alan adında bu süre daha uzun olabilir. Reklam ise ödeme yaptığınız gün trafik getirir, ödemeyi kestiğinizde durur. İkisi birbirinin alternatifi değil, farklı zaman ölçeklerinde çalışan iki araçtır. Size \'iki haftada ilk sayfa\' diyen bir teklif alırsanız, bunun gerçekçi olmadığını bilin. Biz baştan gerçekçi bir takvim veriyoruz; çünkü yanlış beklentiyle başlayan iş ilişkisi üçüncü ayda kopuyor.',
      },
      {
        h2: 'Ölçemediğiniz şeyi yönetemezsiniz',
        body: 'Pazarlama harcamasının değerlendirilebilmesi için önce ölçümün doğru kurulması gerekir: hangi kanaldan gelen ziyaretçi ne yapıyor, form dolduranların kaçı gerçek talebe dönüşüyor, bir müşteri edinmenin maliyeti ne. Analitik ve dönüşüm takibi kurulmadan yapılan reklam harcaması, sonucunu göremediğiniz bir yatırımdır. Çalışmaya genellikle bu altyapıyı kurarak başlıyoruz; ilk aydaki en değerli çıktı çoğu zaman kampanya değil, artık neyin işe yaradığını görebiliyor olmanızdır.',
      },
      {
        h2: 'İçerik, arama görünürlüğünün temelidir',
        body: 'Arama motorlarında kalıcı yer edinmenin teknik kısayolu yoktur. Sıralamayı belirleyen şey, kullanıcının sorusuna gerçekten cevap veren içeriktir. Bu, rakiplerin yazdığını farklı kelimelerle tekrarlamak değil; fiyatı etkileyen faktörleri açıklamak, karşılaştırma yapmak, gerçek soruları cevaplamak anlamına gelir. Böyle bir içerik hem sıralamaya girer hem de sayfaya gelen ziyaretçiyi müşteri adayına dönüştürür. Yapay zekayla toplu üretilmiş, kontrolden geçmemiş içerik ise kısa vadede hacim, uzun vadede güven kaybı üretir.',
      },
      {
        h2: 'Sürdürülebilir yöntemler, kısayol değil',
        body: 'Toplu satın alınan bağlantılar, otomatik yorumlar ve yapay trafik kısa vadede rakam üretebilir; ancak arama motorlarının yaptırımına açıktır ve alınan ceza çoğu zaman kazanılandan pahalıya mal olur. Kullandığımız yöntemler kalıcı olanlardır: teknik sağlamlık, doğru yapılandırılmış içerik, gerçek dijital varlıklar ve zamanla biriken otorite. Bu yol daha yavaştır, karşılığında geriye dönük risk bırakmaz.',
      },
    ],
    faq: [
      { question: 'SEO çalışmasının sonuçları ne zaman görülür?', answer: 'Teknik düzeltmelerin etkisi haftalar içinde görülebilir. İçerik ve otorite çalışmalarının sıralamaya yansıması genellikle 4-6 ayı bulur; yeni bir alan adında bu süre daha uzun olabilir çünkü arama motorlarının siteye güven geliştirmesi zaman alır. Rekabetin düşük olduğu uzun kuyruk sorgularda ilk hareketler daha erken görülür.' },
      { question: 'SEO mu, reklam mı tercih etmeliyim?', answer: 'Acil satışa ihtiyacınız varsa reklam, kalıcı ve zamanla ucuzlayan trafik istiyorsanız SEO. Bütçe elverdiğinde en sağlıklısı ikisini birlikte yürütmektir: reklam kısa vadede talep üretirken SEO altyapıyı kurar. Bütçe kısıtlıysa ve zaman varsa SEO ile başlamak uzun vadede daha yüksek getiri sağlar.' },
      { question: 'Sosyal medya yönetimi satışa dönüşür mü?', answer: 'Doğrudan satış beklentisi çoğu B2B iş için gerçekçi değildir; sosyal medyanın asıl işlevi bilinirlik, güven ve hatırlanabilirliktir. Karar süreci uzun olan hizmetlerde müşteri sizi aylar önce görüp, ihtiyaç doğduğunda aramaya başlar. Ölçmesi zor ama etkisi gerçek olan bu katkıyı, tek başına \'kaç satış geldi\' sorusuyla değerlendirmek yanıltıcı olur.' },
      { question: 'Google Ads bütçesi ne kadar olmalı?', answer: 'Sektöre ve rekabete göre tıklama maliyetleri büyük fark gösterdiği için tek bir rakam vermek doğru olmaz. Sağlıklı yaklaşım, dar bir anahtar kelime grubuyla ölçülebilir bir bütçede başlamak, tıklama başına maliyet ve dönüşüm oranı verisi biriktikten sonra bütçeyi bilinçli artırmaktır. Veri olmadan yapılan yüksek bütçeli başlangıçlar genellikle pahalı bir öğrenme sürecine dönüşür.' },
      { question: 'Çalışmanın sonuçlarını nasıl takip edeceğiz?', answer: 'Analitik ve arama konsolu kurulumu yapılır; hangi sorgulardan geldiğiniz, hangi sayfaların çalıştığı ve form dönüşümleri düzenli olarak raporlanır. Amacımız raporun anlaşılır olması: sıralama tablosu değil, işinize dokunan sayılar. Neyin çalışmadığını da aynı açıklıkla paylaşırız.' },
    ],
    subServices: [
      {
        title: 'SEO', slug: 'seo', image: '🔍', icon: 'search',
        description: 'Arama motorlarında üst sıralara çıkmanızı sağlıyoruz. Teknik SEO, içerik stratejisi ve link building.',
        longDescription: 'Teknik SEO denetimi, anahtar kelime stratejisi, içerik optimizasyonu ve link building ile organik arama sonuçlarında sürdürülebilir üst sıra performansı sağlıyoruz. Core Web Vitals optimizasyonu, structured data markup ve crawl budget yönetimi ile sitenizin arama motoru botları tarafından en verimli şekilde taranmasını sağlıyoruz.',
        features: ['Kapsamlı teknik SEO denetimi', 'Anahtar kelime araştırması & strateji', 'İçerik optimizasyonu & on-page SEO', 'Link building & off-page SEO', 'Core Web Vitals optimizasyonu', 'Local SEO & Google Business'],
        process: ['Site denetimi ve rakip analizi', 'Anahtar kelime stratejisi ve içerik planı', 'Teknik ve on-page optimizasyonlar', 'Link building ve aylık performans raporlama'],
        benefits: ['Organik trafikte ortalama %150 artış', 'Sürdürülebilir ve ücretsiz trafik kaynağı', 'Hedef anahtar kelimelerde ilk sayfa sıralaması'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'SEO sonuçları ne kadar sürede görülür?', answer: 'SEO organik ve sürdürülebilir bir süreçtir. İlk iyileşmeler 2-3 ayda görülmeye başlar, anlamlı sonuçlar 4-6 ayda elde edilir. Rekabetçi sektörlerde 6-12 ay sürebilir.' },
          { question: 'Teknik SEO nedir ve neden önemlidir?', answer: 'Teknik SEO, sitenizin arama motorları tarafından taranabilirliğini, indekslenebilirliğini ve performansını optimize etmeyi kapsar. Hızlı yükleme, mobil uyumluluk, düzgün URL yapısı ve schema markup gibi faktörleri içerir.' },
          { question: 'SEO ve Google Ads arasındaki fark nedir?', answer: 'SEO organik (ücretsiz) arama sonuçlarında sıralama sağlarken, Google Ads ücretli reklam alanlarında görünürlük sağlar. SEO uzun vadeli sürdürülebilir sonuç, Google Ads ise anlık trafik sağlar. İkisinin birlikte kullanılması en etkili stratejidir.' },
          { question: 'Yerel SEO (Local SEO) nedir?', answer: 'Yerel SEO, işletmenizin bulunduğu bölgedeki aramalarda görünürlüğünü artıran optimizasyon sürecidir. Google Business profili, yerel dizinler ve konum bazlı anahtar kelimeler ile bölgesel müşterilerinize ulaşmanızı sağlar.' },
        ],
        metaTitle: 'SEO Hizmetleri | Arama Motoru Optimizasyonu | BERACORE',
        metaDescription: 'Google\'da üst sıralara çıkın. Teknik SEO, içerik optimizasyonu, link building, Local SEO ile organik trafikte %150 artış. BERACORE SEO ajansı.',
      },
      {
        title: 'Sosyal Medya Yönetimi', slug: 'sosyal-medya-yonetimi', image: '📣', icon: 'megaphone',
        description: 'Sosyal medya hesaplarınızı profesyonelce yönetiyoruz.',
        longDescription: 'Instagram, TikTok, LinkedIn, X ve Facebook hesaplarınız için stratejik içerik planı, profesyonel görsel ve video üretimi, topluluk yönetimi ve performans analitiği sunuyoruz. Marka sesinizi tüm platformlarda tutarlı yansıtırken etkileşim oranlarını sistematik olarak artırıyoruz.',
        features: ['Stratejik içerik planı & takvim', 'Profesyonel görsel & video üretimi', 'Topluluk yönetimi & moderasyon', 'Performans analitiği & raporlama', 'Influencer iş birliği yönetimi', 'Kriz iletişimi & itibar yönetimi'],
        process: ['Marka analizi ve strateji oluşturma', 'İçerik takvimi ve görsel üretim', 'Yayınlama, etkileşim ve topluluk yönetimi', 'Aylık analiz, raporlama ve strateji güncelleme'],
        benefits: ['Etkileşim oranlarında ortalama %200 artış', 'Tutarlı ve profesyonel marka iletişimi', 'Organik takipçi büyümesi ve topluluk oluşturma'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'Hangi sosyal medya platformlarını yönetiyorsunuz?', answer: 'Instagram, TikTok, LinkedIn, X (Twitter), Facebook, YouTube ve Pinterest dahil tüm büyük platformları yönetiyoruz. İhtiyacınıza göre platform seçimi yapıyoruz.' },
          { question: 'Aylık kaç içerik üretilir?', answer: 'Pakete göre değişmekle birlikte aylık 20-60 arasında görsel, video ve story içeriği üretiyoruz. Reels, TikTok ve carousel içerikler dahildir.' },
          { question: 'İçerik stratejisi nasıl belirleniyor?', answer: 'Hedef kitle analizi, rakip araştırması, trend analizi ve marka kimliğinize dayanarak özel içerik stratejisi oluşturuyoruz. Aylık takvim ile planlı ve tutarlı yayın yapıyoruz.' },
          { question: 'Raporlama ne sıklıkla yapılır?', answer: 'Aylık detaylı performans raporu sunuyoruz. Takipçi büyümesi, etkileşim oranları, erişim, tıklamalar ve dönüşüm metrikleri ile şeffaf raporlama yapıyoruz.' },
        ],
        metaTitle: 'Sosyal Medya Yönetimi | İçerik Üretimi | BERACORE',
        metaDescription: 'Profesyonel sosyal medya yönetimi: içerik üretimi, topluluk yönetimi, influencer iş birlikleri. Instagram, TikTok, LinkedIn. BERACORE dijital pazarlama.',
      },
      {
        title: 'Google & Meta Reklamları', slug: 'google-meta-reklamlari', image: '📈', icon: 'trending',
        description: 'Google Ads ve Meta reklamlarıyla hedef kitlenize ulaşın. ROI odaklı kampanya yönetimi.',
        longDescription: 'Google Search, Display, Shopping ve YouTube reklamları ile Meta (Facebook & Instagram) kampanyalarını ROI odaklı yönetiyoruz. Detaylı hedef kitle analizi, A/B test stratejileri ve conversion tracking ile reklam bütçenizin her kuruşundan maksimum verim alıyoruz.',
        features: ['Google Ads (Search, Display, Shopping)', 'Meta Ads (Facebook & Instagram)', 'YouTube & video reklam yönetimi', 'Remarketing & retargeting stratejileri', 'A/B test & sürekli optimizasyon', 'Conversion tracking & attribution'],
        process: ['Hedef kitle araştırması ve strateji', 'Kampanya oluşturma ve kreatif tasarım', 'Lansman, A/B test ve optimizasyon', 'Performans raporlama ve bütçe optimizasyonu'],
        benefits: ['Reklam harcamasında ortalama 4x ROI', 'Doğru kitleye doğru mesaj ile düşük CPA', 'Şeffaf raporlama ve ölçülebilir sonuçlar'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'Google Ads ve Meta Ads arasındaki fark nedir?', answer: 'Google Ads aktif olarak ürün/hizmet arayan kullanıcılara ulaşırken (arama niyeti), Meta Ads ilgi alanı ve demografik hedefleme ile potansiyel müşterilere ulaşır (keşif). İkisinin birlikte kullanımı en etkili stratejidir.' },
          { question: 'Minimum reklam bütçesi ne olmalıdır?', answer: 'Etkili kampanyalar için minimum aylık bütçe sektöre göre değişir. Genel olarak başlangıç için makul bir bütçe ile başlayıp performansa göre artırmayı öneriyoruz. Detaylı bilgi için danışmanlık alabilirsiniz.' },
          { question: 'ROI nasıl ölçülüyor?', answer: 'Google Analytics, Meta Pixel, conversion tracking ve attribution modelleri ile her reklam kanalının ve kampanyanın gelir üzerindeki etkisini hassas şekilde ölçüyoruz.' },
          { question: 'Remarketing nedir?', answer: 'Remarketing, web sitenizi ziyaret eden ancak dönüşüm gerçekleştirmeyen kullanıcılara farklı platformlarda tekrar reklam gösterme stratejisidir. Dönüşüm oranlarını önemli ölçüde artırır.' },
        ],
        metaTitle: 'Google Ads & Meta Reklam Yönetimi | BERACORE',
        metaDescription: 'Google Ads ve Meta (Facebook/Instagram) reklam yönetimi. ROI odaklı kampanya stratejisi, A/B test, remarketing. 4x ROI. BERACORE dijital reklam ajansı.',
      },
      {
        title: 'İçerik Pazarlama', slug: 'icerik-pazarlama', image: '✍️', icon: 'pen',
        description: 'Blog, makale, video ve infografik ile markanızın otoritesini artırın.',
        longDescription: 'SEO uyumlu blog yazıları, sektör makaleleri, e-kitaplar, video içerikler ve infografikler ile markanızı sektörünüzde otorite haline getiriyoruz. İçerik stratejisi ve editorial takvim ile tutarlı ve planlı içerik üretimi sağlıyor, e-mail pazarlama kampanyalarıyla mevcut müşterilerinizi elde tutuyoruz.',
        features: ['SEO uyumlu blog & makale yazımı', 'Video içerik prodüksiyonu', 'E-kitap & whitepaper hazırlama', 'E-mail pazarlama kampanyaları', 'İçerik takvimi & editorial planlama', 'İçerik performans analitiği'],
        process: ['İçerik stratejisi ve persona bazlı planlama', 'İçerik üretimi ve editorial review', 'Çoklu kanal dağıtım ve promotion', 'Performans analizi ve strateji optimizasyonu'],
        benefits: ['Organik trafikte uzun vadeli sürdürülebilir büyüme', 'Sektörde güvenilir otorite konumlandırma', 'Lead generation ve müşteri sadakati artışı'],
        stats: [{ value: 'REST · GraphQL', label: 'API Standartları' }, { value: 'Webhook', label: 'Olay Tabanlı Akış' }, { value: 'Hata Toleransı', label: 'Yeniden Deneme' }, { value: 'İzlenebilir', label: 'Çağrı Kayıtları' }],
        faq: [
          { question: 'İçerik pazarlama neden önemlidir?', answer: 'İçerik pazarlama, potansiyel müşterilerinize değerli bilgi sunarak güven oluşturur, SEO performansınızı artırır ve uzun vadeli organik trafik sağlar. Reklam yerine değer sunarak marka otoritesi oluşturursunuz.' },
          { question: 'Blog yazısı ne sıklıkla yayınlanmalıdır?', answer: 'SEO etkisi için haftada en az 1-2 kaliteli blog yazısı öneriyoruz. Tutarlılık, sıklıktan daha önemlidir. İçerik takvimi ile planlı yayın stratejisi oluşturuyoruz.' },
          { question: 'İçerik SEO uyumlu nasıl yazılır?', answer: 'Anahtar kelime araştırması, başlık optimizasyonu, meta etiketleri, iç linkler, okunabilirlik ve structured data ile SEO uyumlu içerikler üretiyoruz. Google E-E-A-T kriterlerine uygun, değer katan içerikler yazıyoruz.' },
          { question: 'E-mail pazarlama hâlâ etkili mi?', answer: 'Evet. E-mail pazarlama hâlâ en yüksek ROI sunan dijital pazarlama kanallarından biridir. Kişiselleştirilmiş kampanyalar, segmentasyon ve otomasyon ile %45+ açılma oranı elde ediyoruz.' },
        ],
        metaTitle: 'İçerik Pazarlama & Blog Yazımı | BERACORE',
        metaDescription: 'SEO uyumlu içerik pazarlama hizmetleri. Blog yazımı, video içerik, e-kitap, e-mail pazarlama. Marka otoritesi oluşturma. BERACORE içerik ajansı.',
      },
    ],
  },
];
